### ISSUE TITLE
User presentation window and sorting function?

### ISSUE THREAD

**Issue by ClaesFredo** [leihs/leihs#100]
The idea here deals less with Leihs system functionality than usage. For what it is worth:
A) Why not add a new type of Category which is, new items, most popular, least us ed, or just random picks? I got this idea as I showed Leihs to a colleague at my old department and he eanted to use Leihs both for instruments (as I do) and for the department Library. 
B) On the same note, why not be able to search items based on descriptors? I provide weight and som other data for my instruments, but searching could be made on dimensions etc. 

Just a thought. Feel free to ignore it. 
Claes

**Comment by psy-q** [comment]
An advanced search was always shot down in the past because apparently "people never use advanced search systems anyhow". I don't really agree with that, it's probably only 5% of the users who would use it, but they would be getting a lot out of such a feature.

We do have the data for that, just not the search algorithm. I personally don't see this being developed at ZHdK, but if anyone else wants to have a go, feel free!

I did create a Pivotal ticket at ZHdK for A), though: https://www.pivotaltracker.com/story/show/105649738

**Comment by nadjaweisskopf** [comment]
@ClaesFredo Please check the new feature called "Advanced Search". The new feature gives the possibility to search in all fields of the item - in combination.
