### ISSUE TITLE
Inventory Pool / Users / Roles

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1000]
Rename the filter "Any" to "Any role"
https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/users/?account_enabled=&is_admin=&org_id=&page=1&per-page=50&term=&role=any

Rename the filter "Any" to "Any role"
https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/groups/?page=1&per-page=50&org-member=&term=&including-user=nadja.weisskopf%40zhdk.ch&role=any

Add a "remove" button in column "Roles" if a role is selected. Then the user does not have to edit the group first. 
https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/groups/?page=1&per-page=50&org-member=&term=&including-user=nadja.weisskopf%40zhdk.ch&role=customer

Why are the names of the inventory pools italic? 
https://test.leihs.zhdk.ch/admin/inventory-pools/

The link "group roles" is missing on the top menu. 
https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/users/7039559d-28e7-4303-87ff-f29d06eaed6e

**Comment by DrTom** [comment]
I believe e.g. "any role" is misleading; maybe rather "any role or none role". A general alternative would be something like "no filter"  or just blank "". 

Italics (em) is used for "name"-like things. It is used in headers (quite consistently); inside tables it might be not very constistent. It is in particular helpful if the "name linke thing" is not a link.

**Comment by DrTom** [comment]
Role Filter: 
1. "all" is missing 
2. rename "any" to " "any role"

**Comment by DrTom** [comment]
Check how inlined editing and remove button "feels".

**Comment by DrTom** [comment]
"Add group role"  would be convenient if link opens with "any" filter.

**Comment by DrTom** [comment]
@nadjaweisskopf update and details about the roles selector:  `any` had the meaning of `any role or none`.  It never showed users without role because for "Ausleihe Toni Areal" there are not any users without roles (almost), because of this "add new user hook".  It is now renamed `(any role or none)` to make  this more explicit.
The "any role" or "some role" in the meaning at least one role isn't missing; because of the hierarchy this is the same as "customer" which is also the default filter.

**Comment by nadjaweisskopf** [comment]
@DrTom ok, we'll see during schooling of the users if they miss a filter called "any role".
