### ISSUE TITLE
retire legacy admin

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1017]
There are some admin-views left in the legacy "admin" app, which should be ported over to the new admin.

**Comment by eins78** [comment]
@nimaai I think we just start with a list of the remaing forms, to get an overview how much work it is. Maybe its to much for the current "polishing new admin" release.

**Comment by nadjaweisskopf** [comment]
Remaining Views that need to be moved to new admin: 
- Buildings (1 view page / 1 edit page)
- Rooms (1 view page / 1 edit page)
- Mail Templates (1 view page / 1 edit page)
- Suppliers (2 view pages / 1 edit page)
- Fields (because it is quit complex we said we would keep this features with it's pages as it is without moving it to admin)

**Comment by nimaai** [comment]
cleanup after all has been moved:
- [ ] remove engine
- [ ] remove reference to engine's routes from core routes
