### ISSUE TITLE
bug: login does not use/enforce CSRF token

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#1038]
steps:
* log into leihs (zhdk) with username & password auth
* look at the request in the browser inspector: no `csrf-token` is sent, yet the login suceeds
* compare with the network request when changing the language: a `csrf-token` is sent!

**Comment by eins78** [comment]
original implementation assumed we only need anti-CSRF once a session exists, which does not seem to be correct in all cases. we'll fix it instead of trying to prove that its safe. ref: https://github.com/OWASP/CheatSheetSeries/blob/ea0b1c8128634cc1e3e081ed7c62780a055da800/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md#login-csrf

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/3cadccf103bd86b307ffdfc079ed7133978763f9
