### ISSUE TITLE
Filename - problem (windows specific)

### ISSUE THREAD

**Issue by tmulzer** [leihs/leihs#104]
I just tried to check out the git-repository to a windows - computer (my fault, I know - won't do that again) ..

error: unable to create file features/personas/dumps/seed_2016-08-10T12:29:26+02:00.sql (Invalid argument)

.. was the answer.
Filenames with a colon (:) are illegal on windows-systems.

It's not mission-critical, but may be resolved easily.

Kind regards,
Tasso

**Comment by psy-q** [comment]
Since leihs doesn't run on Windows, what are you trying to accomplish by cloning onto Windows? If you are running leihs inside a virtual machine on Windows, can't you check out the code in there?

The timestamps in all of leihs' SQL dump filenames (not just the seed dumps) are in ISO8601 format for standard-compliance and easy parsing. Changing this would require changing the places where they are parsed, perhaps agreeing on and specifying a custom datetime parse format string, and it would probably make the timestamps less legible to humans. Plus break ISO8601 conformance. 

I think the benefits of doing that would have to outweigh the drawbacks. RIght now I can't see any  benefits because leihs can't run on Windows.

It probably never will, unless someone steps up to port it to JRuby and replace all the native gems with JRuby or Java libraries and maintain that compatibility, or port it to Windows in such a way that all the native gems it uses have precompiled Windows versions available and won't have to be compiled during installation. Otherwise you'd need all the libraries, header files etc. on Windows as well as a C/C++ compiler (mingw would work).

So it's probably not such a bad thing that cloning won't even work on Windows :)
