### ISSUE TITLE
Improve Calendar

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1136]
Calendar features which need modification of `@leihs/calendar`
- [x] Dates which are only no-pickup/return have the classes `disabled disabled-start disabled-end` (pseudo code) no matter if the item is generally available or not. E.g. in the 'Contraints" select 20 to 22: the 21 should get red but won't (false negative). The fix for this would lead to false positives (e.g. for 9 to 12). 
- [x] Disabled dates should not be blocked for selection in the UI (controlled by prop `allowSelectionOfDisabledDates`).  
- [x] Calendar shown month does not follow a prop-driven month change (might be solvable with the `key` trick, see `DatePicker`)

**Comment by eins78** [comment]
I am trying out the state from https://github.com/leihs/leihs-ui/pull/43 in the app and found some weird cases:

1. the lazy loading still is not quite right, when navigation fast a month starts out as selectable, then unselectable while its loading. it looks like a problem in the app though

2. look at dezember 2023 for this model: https://mfa.ruby.zhdk.ch/app/borrow/models/1aabaeb8-c1a5-5c8e-858a-aa0bddf469dd
    * everything is blocked: 
       <img width="440" alt="Screen Shot 2021-08-19 at 12 00 10" src="https://user-images.githubusercontent.com/134942/130049935-d7518344-2c65-499a-b384-a0e6cb8304c8.png">
    * but when selected, the bar is blue, also looks like it starts on 01.12. not 30.11., yet there is a cross on 30.11.
      <img width="450" alt="Screen Shot 2021-08-19 at 11 58 57" src="https://user-images.githubusercontent.com/134942/130049941-9d0e1c7b-3375-40ad-9463-c6ddd573a7f1.png">

**Comment by urs-van-binsbergen** [comment]
> 2. look at dezember 2023 for this model: https://mfa.ruby.zhdk.ch/app/borrow/models/1aabaeb8-c1a5-5c8e-858a-aa0bddf469dd
This is exactly the issue we are adresssing with this task (first sub-task checkbox).

**Comment by eins78** [comment]
nitpicks, actually from new `DatePicker`, but only visual so i'll add it here:

- the blue border of the text input is dependent on its `focus` state. for clarity think in this case of a "combined" input it should also be blue as long as the calendar is open (because the whole input still has focus). what do you think?
<img width=360 src="https://user-images.githubusercontent.com/134942/130064638-55e93ea5-6c3d-44a0-8c72-7f7f82cbdb9c.jpeg" />

- the rounded borders dont fit the dropdown, should not be rounded when its open

![Screen Shot 2021-08-19 at 14 00 16](https://user-images.githubusercontent.com/134942/130065265-61abc05e-99a8-4cc0-b30b-de6ce4b7ceca.png)

**Comment by urs-van-binsbergen** [comment]
Summary of open items from above comments:
- [ ] "the lazy loading still is not quite right, when navigation fast a month starts out as selectable, then unselectable while its loading. it looks like a problem in the app though"
  - To discuss / more info needed
- [ ] Visually integrate calendar in date field

**Comment by eins78** [comment]
done in https://github.com/leihs/leihs-ui/pull/44 and https://github.com/leihs/leihs-ui/pull/47
