### ISSUE TITLE
my rentals: repeat / reactivate order

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1174]
cart needs to be finished first

**Comment by urs-van-binsbergen** [comment]
https://leihs-styleguide-git-uvb-repeat-order-leihs1.vercel.app/iframe.html?id=mobileapp-wireframes-meine-bestellungen-wiederholen--wiederholen&args=&viewMode=story

**Comment by nadjaweisskopf** [comment]
to think about: 
- if you already have items in the cart, leihs just adds the new items of the list
- if you are in an order and you change the user, should you be able to delete the order as from user A as user B?

**Comment by urs-van-binsbergen** [comment]
The current implementation is deployed on the `uvb` server and can be tested

I also updated the story (link see below) to show the variant with one date range calendar instead of 2 separate date pickers.  
https://leihs-styleguide-git-uvb-repeat-order-leihs1.vercel.app/iframe.html?id=mobileapp-wireframes-meine-bestellungen-wiederholen--wiederholen&args=&viewMode=story

**Comment by nadjaweisskopf** [comment]
discussed today: 
- place (Option) behind the option name on the my order page
- show "3 options can't be reserved ..." when adding to the cart

**Comment by urs-van-binsbergen** [comment]
The feature is merged, the feature can be tested. There are two spin-off tickets: #1339 and #1340
