### ISSUE TITLE
Show link text in model description as link

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1253]
Show link text in model description as link in borrow section. 

In legacy, this was not possible either. But it would be great, if the link text would be a real link. 

I tried to adjust the link text but in any case the link is just shown as text

https://www.cetus3d.com
www.cetury3d.com

F.e. https://staging.leihs.zhdk.ch/borrow/models/081032e2-8221-49f8-8963-9b687ec8c07d?

**Comment by eins78** [comment]
In Madek, we use the[ `linkify`](https://www.npmjs.com/package/linkifyjs) module for this: 
https://github.com/Madek/madek-webapp/blob/b0055d400a478052893bc700b203883efb801e5c/app/assets/javascripts/react/decorators/MetaDatumValues.cjsx#L91-L105

We could adopt the same solution almost 1:1, i'd only change `target: '_self'` to open in a new tab instead, and remove the `ftp` part from the validation. Then it would work for:

* http://www.example.com
* http://example.com
* https://www.example.com
* https://example.com
* www.example.com

but NOT:

* example.com (we will likely never support this because it creates to many unintended link, either by typos like a missing space ("cool `equipment.is` the best on the market") or new domains endings (something.pizza).
