### ISSUE TITLE
External SSR rendering via node does not exit 

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#1278]
The external ssr rendering produces the desired output but does not exit after completion. 

Seems to be platform or node version related: problem exists at least on MacOS with macports node js version 16.13.1. 

Solution could be as simple as a missing equivalent of  `(system/exit 0)` after the rendering is done.

**Comment by eins78** [comment]
I had a quick look, regarding the actual rendering the code path is very simple and there are no async functions, promises, callbacks that could be mishandled.

* https://github.com/leihs/leihs-ui/blob/251eed5b9f94729f3f442219c9448fc244c746c7/ssr-cli.js#L10
* https://github.com/leihs/leihs-ui/blob/251eed5b9f94729f3f442219c9448fc244c746c7/src/server-side.js#L14
* https://reactjs.org/docs/react-dom-server.html#rendertostring

Since you are observing hangs, something else must be wrong; i suspect the `process.stdout.write` call could be the culprit. The reason why it broke recently could be nodejs version (unlikely), or something about the shell/pipe/etc setup where its called (I remember something about hanging pipes that need to be flushed when the consumer is not not reading from them) 

* https://nodejs.org/dist/latest-v16.x/docs/api/process.html#processstdout
* some notes https://nodejs.org/dist/latest-v16.x/docs/api/process.html#a-note-on-process-io

Reading the docs I dont think adding a `process.exit(0)` somewhere would help, because then some output might be missing. We could still do it after a "next tick" timeout to be sure, but thats a shot in the dark.

@DrTom: 
* next steps: how do i reproduce your issue?
* an aside because we opened this barrel ;) React now also has async rendering. That would only be of use in practice if we can somehow "stream" this through the whole stack, non-blocking. Meaning as soon as React send the first bytes the webserver starts delivering them.

**Comment by eins78** [comment]
@urs-van-binsbergen reports: something is calling `requestAnimationFrame` which of course fails in node. next step: find out why.

**Comment by DrTom** [comment]
@eins78 to reproduce from the command line: 
```
node resources/leihs-ssr.js render Navbar '{"csrfToken":{"value":"acb09b49-7447-4988-8140-0402cf201714","name":"csrf-token"},"config":{"appTitle":"leihs","appColor":"gray","me":null,"subApps":{"admin":false},"locales":[{"name":"English (UK)","locale":"en-GB","active":true,"isDefault":true,"isSelected":true},{"name":"English (US)","locale":"en-US","active":true,"isDefault":false,"isSelected":false},{"name":"Deutsch","locale":"de-CH","active":true,"isDefault":false,"isSelected":false},{"name":"Züritüütsch","locale":"gsw-CH","active":true,"isDefault":false,"isSelected":false}]}}'
```
Same as calling it from inside the JVM process: it produces the proper output but then just doesn't exit.

**Comment by eins78** [comment]
steps to reproduce:

```sh
cd leihs-ui
nvm use 16 && npm ci && sh test/test-ssr-cli.sh 
```
