### ISSUE TITLE
Mac OS X

### ISSUE THREAD

**Issue by nkuhan** [leihs/leihs#132]
Can I install it on Mac OS X

**Comment by psy-q** [comment]
You can try, if you can get [the dependencies](https://github.com/leihs/leihs/wiki/leihs-Admin-Guide) working. Officially only Debian-based GNU/Linux distros are supported. Well, only Debian 8.0 really,  there is sketchy support for Ubuntu 16.04 in the [Ansible playbook](https://github.com/leihs/ansible-leihs-setup) and at least the base setup is documented for RedHat-based distros.

Since on OS X there are half a dozen different ways to get the dependencies, documenting them all would be quite a lot of work, but if someone wants to pick up that work, feel free to [edit the wiki](https://github.com/leihs/leihs/wiki/leihs-Admin-Guide).
