### ISSUE TITLE
 `rbenv: version `2.3.0' is not installed 

### ISSUE THREAD

**Issue by nkuhan** [leihs/leihs#133]
I already installed **rbenv: version 2.3.1**
when I run 
`/leihs/leihs-3.38.0$ RAILS_ENV=production bundle exec rake db:create db:migrate db:seed`

it asked me
`rbenv: version `2.3.0' is not installed (set by /home/kuhan/leihs/leihs-3.38.0/.ruby-version)
`

**Comment by psy-q** [comment]
I'm not even sure why there is a .ruby-version file anymore. The docs all say to use 2.3.1. You can change the content of .ruby-version to "2.3.1". @nimaai is there a reason the .ruby-version file sticks to 2.3.0 while the actual instances run on 2.3.1?

**Comment by nimaai** [comment]
The original idea behind was to ensure that developers on their machines, our test infrastructure and production server use the same rbenv version and thus should be part of the code. The upgrade of this file would ensure that the particular ruby version was installed everywhere. 

This goal was only partly achieved and currently this file serves probably no purpose. But this ideal goal still exists.

**Comment by psy-q** [comment]
Then I would guess that it just needs to be ensured that https://github.com/leihs/ansible-leihs-setup and .rbenv-version are in agreement and the goal is reached :)  Should I update .rbenv-version to say 2.3.1 because that's the version that's running without issues on a dozen instances?

**Comment by nimaai** [comment]
Yes, cool. That would ensure same ruby version between developer machines and production server. 

But what about the executors? I am not sure after the ruby configuration setup was changed on Cider some while ago...

**Comment by psy-q** [comment]
Ah. Didn't think of that one. Let's ask @drtom .

**Comment by DrTom** [comment]
So, the recommended way is to rather use the `ruby-install` trait on the ci-executors. You can use `ruby-install` to install rubies conveniently. Setting env vars from there on is your business!  `rbenv` is still around but it has a number of drawbacks. It will never be in the path by default (that would cause too much trouble) and upgrading it so it supports the desired ruby version is also up to you ...

**Comment by psy-q** [comment]
So if Cider ignores it anyhow, I guess it's safe to change. Thanks!

**Comment by DrTom** [comment]
I am not sure because I didn't understand completely. 

But every test which wants to use `rbenv` should make sure `rbenv` is in the state it needs it to be. If necessary it must upgrade `rbenv`  ... 

From a practical standpoint on the `ci2.zhdk.ch` executors: nothing else is using `rbenv` but leihs. So you can do whatever you want with `rbenv` there ;-)

**Comment by psy-q** [comment]
I don't know about the Cider config for leihs, I'm guessing if the normal way is to use ruby-install and it sets $RUBY to 2.3.1 there (if that's how it works), we're all good. 

The leihs docs always point to 2.3.1 and if I understand @nimaai correctly, the `.ruby-version` file is now mostly to make sure all developers are on the same Ruby. It has no effect in production (Phusion Passenger sets the Ruby version and completely ignores .ruby-version) or on Cider, so what's left is only developer machines.

Probably still makes sense there, no? Since the version in the docs could be for production, which could be older than what the developers need to use locally if they're working on a feature branch, Rails upgrade, etc.

I've pushed something to https://github.com/leihs/leihs/tree/rca/change_ruby_version that you can merge if you like.

**Comment by nimaai** [comment]
> Probably still makes sense there, no?
If it can't be used for production and on Cider-CI it's not the recommended way anymore, then no. I will remove the file from our repo.

**Comment by DrTom** [comment]
@nimaai lets have a look tomorrow, OK?

**Comment by nimaai** [comment]
@DrTom ok

**Comment by psy-q** [comment]
I think either way is fine. We just need to let people know which Ruby fits with which leihs, and I'm guessing that wouldn't change even if we switched to JRuby. Unless we bundle JRuby, of course.

**Comment by nimaai** [comment]
It's not a crucial point at the present moment at all, by the way. We will decide if and how we want to satisfy this goal in long term after we have refactored our leihs setup in near feature.

**Comment by psy-q** [comment]
It came up because @nkuhan tried to run a local non-production server, which is something no one does in production, but it can't be bad to clean it out if it's no longer needed.
