### ISSUE TITLE
Missing label in filter

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1338]
The search term and the filter label are missing - I get an error: 

![label filter](https://user-images.githubusercontent.com/3356016/161500207-3334af2f-e418-4b5f-829c-11f0db2ba812.jpg)

**Comment by urs-van-binsbergen** [comment]
My thoughts: 
- The cause of the above bug is that `::translate/i18n-locale` (`.-code`) is passed to `ModelSearchFilter`, which is `de` instead of `de-CH` (fix: pass `::translate/locale-to-use`) 
- The underlying problem is that the naming of the sub `::translate/i18n-locale` is misleading, it should be called `date-fns-locale`, because thats the only purpose of this.

**Comment by eins78** [comment]
fixed in https://github.com/leihs/leihs/commit/3e1897495ae9f8e7d9c19ad00b9aadcec21a690f
