### ISSUE TITLE
new borrow: improve browser storage handling

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1363]
* try using `sessionStorage` instead of `localS.`
* purge the storage on logout (at least in new borrow, ideally everywhere)
  * try finding bettter lib
  * or copy/paste lib into our shared code

wait for nadjas delegation tests - if a big problem, then we need to solve this before going live - otherwise after going live

**Comment by nadjaweisskopf** [comment]
issue if several tabs are open.

**Comment by nadjaweisskopf** [comment]
Question and discuss, if local storage should be reduced

**Comment by urs-van-binsbergen** [comment]
What was done:
- Clear storage after logout
  - Add script to `render-root-page` view (`shared-cljs`), clearing all session- and localStorage for the origin
  - The root page is redirect to after logout, and it is only rendered when the user is not logged in, so this should be technically OK
- Generally use `sessionStorage` instead of `localStorage`
  - Session storage is not supported by the library we use: `akiroz/re-frame-storage`. Copied the source file and added session storage supports (flag argument)
  - Renamed the "facade" `local_storage.cljs` to `browser_storage.cljs` and added support for session storage. The db key stays `:ls` in order to avoid touching feature code. Local storage is mounted under the key `:ls2` (not used as of now).
  - Resulting issue: `current-delegation` is lost when user opens link in new window which is unexpected and could lead to quite some user irritation.  
    - Solution: Implemented `profile-tracker`, a mechanism to propagate the last selected delegation to new windows via local storage
  - Created specs to check a) windows have an independent state now and b) new windows keep the last selected delegation

**Comment by urs-van-binsbergen** [comment]
@nadjaweisskopf How to test: 
- Login with your account
- Switch to a delegation profile
- Open a new tab with the borrow app (for instance by right-clicking on a link > "Add in new tab")
- The new tab will have the same delegation profile as selected before
- Change to a different profile in the second tab
- Switch back to first tab and F5 refresh - the profile will not have changed (as it would have been the case before)
