### ISSUE TITLE
Template Feature for New Borrow

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1431]
It should be possible to add models from a template to the shopping cart. 

Following steps are needed: 
- Tile to add models from template
- page to choose specific template
--> show name of template and list of models for each template 
- Give possibility to set start and end date (already existing "add item" dialogue
- Logic: add model to cart if: model has 1 or more lendable items
- Logic: do not add model to cart if: model does not have at least one lendable item
- show add button to add models from template to shopping cart
- show success message

Any problems or wishes regarding availability or amount shall be dealt with per line in the shopping cart.

**Comment by urs-van-binsbergen** [comment]
Branch: https://github.com/leihs/leihs/compare/uvb/templates

Not mergable yet, because it does not work correctly for delegation profiles yet
- First to be fixed: https://github.com/leihs/leihs/issues/1460, then:
  - Check: User should not be able to view templates when neither the personal profile nor his delegation profiles have access to the defining inventory pool
  - Check: In template detail reservability of items must match the current profile (currently always personal profile)
  - Check: Add items in delegation profile
  - Include all this in spec

**Comment by urs-van-binsbergen** [comment]
On Thursday 27 October we decided that the detail view of a template should show an error when the current profile does not have access to (even if one of the other profiles of the user could access it).

**Comment by nadjaweisskopf** [comment]
@nadjaweisskopf to test on UVB
