### ISSUE TITLE
creating a new user -> password_sign_in_enabled is true in any case

### ISSUE THREAD

**Issue by winampdevil** [leihs/leihs#1488]
#### Expected behaviour or future wish
when i create a new user and didn't check the box "Password sign-in (password_sign_in_enabled)"
and i click "Save"
then the account property "PW Sign-in" should be "no" 

#### Issue or wish reported by
winampdevil

#### Current behaviour
when i create a new user and i didn't check the box "Password sign-in (password_sign_in_enabled)"
and i click "Save" for the first time,
then the account property "PW Sign-in" is "yes" in any case
If i go back to the account-editor, the box "Password sign-in (password_sign_in_enabled)" is also checked.
Now, If i uncheck this box and "save", the property "PW Sign-in" is "no"

#### Specifications
- Leihs version: 6.4.1 (also in ZHdK - Demo @v6.7.0)
- Browser version: Chrome 107

**Comment by neoheat** [comment]
The behavior while adding a new user via admin console is that the `password_sign_in_enabled` is automatically set by default. If a user is created and edited again, the setting is correctly activated.

So, the current behavior is ok. The reason is that if a user is not created via an external authentication system, the password sign in function must be activated. But the function could be optimized in the way that the `password_sign_in_enabled` is enabled by default. 

Will discuss this with the team.

**Comment by neoheat** [comment]
the checkbox `password_sign_in_enabled` is now enabled by default when a user is created.
