### ISSUE TITLE
Empty Models (without Items) not listed in Inventory view

### ISSUE THREAD

**Issue by andypillip** [leihs/leihs#149]
After creating a Model the natural way of doing things is to verify if it's there.

But the inventory view does not list the created Model as long as it's empty.

I understand that there's technical reasons for that, but it's against the user's expectations.

Maybe a solution could be to list Models that the user himself created?

**Comment by andypillip** [comment]
I just learned that there can be different user rights.

Anyway, for users without the rights to see Models this is still an error. Those should at least see their own Models.

**Comment by psy-q** [comment]
Have you tried going to Inventory -> Models and setting the filters to "retired & not retired" so that you can select "used & not used"? The list by default doesn't show models that have no items.

Looks like this (the ugly green background is just because this is from a test instance):

http://i.imgur.com/v7BZj9T.png

It's not that easy to discover and should be improved at some point.

**Comment by andypillip** [comment]
Thank you @psy-q, this works.

I agree that it should be improved. _Retired_ is not a property of a Model, so choosing it to view Models doesn't make sens.

So let's rephrase this issue? (:

**Comment by nadjaweisskopf** [comment]
In this model list the items are shown too... First model, then the items belonging to this model. So the filter "retired & not retired" does make sense. We might need an additional checkbox called "show empty models" which is not set by default. 
We will discuss what is best to do.

**Comment by nadjaweisskopf** [comment]
We need to find a solution for this problem. Stapo and users from ZHdK have asked the same question. 

- We could provide a checkbox on the tabs All/Models/Packages called something like "vacant models" / "unbenutzte Modelle".
- Checkbox is not activated per default
- If checkbox is activated, all other filters disappear or are greyed out.

**Comment by phiku** [comment]
The default filters for the inventory list have "retired" set to "false", therefore "not retired". Retired is a property of items, not models. When you have a new model without any items yet, the model is of course not retired, because a model cannot be retired. It makes no sense at all that choosing from the "retirement" dropdown influences if a model is displayed or not. Now the problem is, it is actually not about "retired". It is about if the selected filters are for items or not. In this case, "retired" is for items. And if the filter is for items, then automatically only "used" models are considered, which somehow is strange, because there is an extra filter for "used".

**Comment by phiku** [comment]
@nadjaweisskopf Do you know if there is a reason why we consider only used models when filters related to items are selected?

**Comment by phiku** [comment]
@nadjaweisskopf There is a new version on test now.

**Comment by nadjaweisskopf** [comment]
@phiku because unused models do not have an item attached and therefor the result list for the item filters don't include unused models.
