### ISSUE TITLE
parse Links and paragraphs in description of detail view

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1520]
#### Expected behaviour or future wish
Entered paragraphs and links in the description of a model should be parsed. Links should open in an new window.

#### Issue or wish reported by
me

#### Current behaviour
paragraphs and links in the description of a detail view of new borrow are not parsed and displayed correct.
In Borrow (legacy), the paragraphs are rendered (though the links not).

#### Steps to reproduce
- open https://test.leihs.zhdk.ch/app/borrow/models/0bdef7dc-c6ab-469c-9270-b04ab2b7dcbb?term=test%20product%20%231520
- see, if paragraphs and links are displayed correctly

#### Specifications
- Leihs version: 6.9.1 
- Browser version: safari

<img width="1361" alt="issue 1520 borrow legacy" src="https://user-images.githubusercontent.com/123965725/231767971-dcee21ac-f52f-4c51-9a9d-f8f75fa032e5.png">
<img width="1470" alt="issue 1520 new borrow" src="https://user-images.githubusercontent.com/123965725/231767997-978e75b2-86e7-4ee0-b630-897ef0a87d44.png">

**Comment by urs-van-binsbergen** [comment]
The "test product" does not seem to exist anymore (probably because prod data was restored meanwhile)?

Here is an existing model with both features (line breaks and links)
new borrow: https://test.leihs.zhdk.ch/borrow/models/e771e086-2f07-42e6-99e4-4d67b91fb90b
legacy borrow: https://test.leihs.zhdk.ch/borrow/models/e771e086-2f07-42e6-99e4-4d67b91fb90b
