### ISSUE TITLE
Switch to new borrow:  update wiki

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1542]

**Comment by nimaai** [comment]
apparently only `Availability`

**Comment by nimaai** [comment]
It concerns [this screenshot](https://github.com/leihs/leihs/wiki/Availability#user-content-use-cases).

The problem is that it is not so easy to get it for the required test data in new borrow, because we use time traveling to past in legacy.

@urs-van-binsbergen could you please create a screenshot in new borrow using exactly the same data as in the old borrow screenshot? to fake it so to say using storybook, or similar.

**Comment by urs-van-binsbergen** [comment]
![new-borrow-calendar-2018-06](https://github.com/leihs/leihs/assets/25439444/ad82b0b0-04a0-4e3b-a9d2-4089feacc841)
![new-borrow-calendar-2018-07](https://github.com/leihs/leihs/assets/25439444/ec7d3630-d932-4694-8d05-a70bb98457d1)

**Comment by urs-van-binsbergen** [comment]
![new-borrow-calendar-2018-06](https://github.com/leihs/leihs/assets/25439444/4a9115cd-fef2-43fa-8fb1-5405dbe0e35c)
![new-borrow-calendar-2018-07](https://github.com/leihs/leihs/assets/25439444/1dc2f453-1efd-4631-8497-d90c528878fb)

**Comment by neoheat** [comment]
a408706..80f9829  lbr/documentation-new-borrow
 
 merge to `master`pending
