### ISSUE TITLE
Switch to new borrow: don't send mails via legacy but use respective libraries for mail templates

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#1544]

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/d33075911627d7c60fe608d50137d2424d58b7e1

**Comment by neoheat** [comment]
since I have now access to the mail catcher accounts of `Staging` and `Test`, I executed the following tests

- ✅ `received` emails are sent only if the respective inventory pool setting is enabled
- ✅ `received` template should be rendered in the system's default language
- ✅ `submitted` email should go to the responsible user's email if the order was done for a delegation
- ✅ fallback to `secondary_email` if the user doesn't have a primary one
- ❌compare the emails between `STAGING` (emails sent by legacy) and `TEST` (emails sent by new borrow)

> There is a difference between STAGING and TEST 
> - the `submitted` email has a different sender
> - the mail subject is in english, despite the chosen user language `german`



@nimaai, please execute the following test by yourself (with modifying the database), I can't test this.
- submitted template should be rendered either in the user's preferred language or the system's one as a fallback

**Comment by neoheat** [comment]
<img width="1261" alt="Staging Mails" src="https://github.com/leihs/leihs/assets/123965725/61171cb5-bca8-4c07-bbb0-886b661e7c45">
<img width="1340" alt="Test Mails" src="https://github.com/leihs/leihs/assets/123965725/58af20ed-5795-4f16-a285-075d0bdd1987">

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/7f3c01c1f4445e6ffb482343ecc87f94827cacff
