### ISSUE TITLE
Leihs legacy issues after PostgreSQL 15 Update

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1569]
In Leihs legacy some tests did not pass. 
https://ci.zhdk.ch/cider-ci/ui/workspace/jobs/e3ca9930-5ce2-4c80-a360-da879883646b

**Comment by nimaai** [comment]
analysis findings so far: i assume every test fails where there is an uncaught exception in rails. the application code relies on the default mechanism of rails to catch and render it.

however, rails behaves differently in every environment:
* `development`: exception is caught and rendered by rails and response with error status 422 is returned.
* `test`: exception is not caught by rails and being propagated to the `audit` middleware and then further until it is caught by `puma` itself. that's why the tests are crashing. browser gets 500 response.
* `production`: same behaviour as in `development` except for a custom rack app for rendering the exception is used (see `errors_controller.rb` and the respective initializer `error_handling.rb`)

**Comment by nimaai** [comment]
correction: 

after running the test on master it seems other test data are used, that's why it's green there. @DrTom your assumption in regards unspecified order of returned rows seems to be true.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs_legacy/commit/cef035c1aec346caf42cee6f391d290a17d0754b

@DrTom
