### ISSUE TITLE
move items into new pool

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#159]
Please move all items for ITZ from
old: Owner = "ZHdK Inventar"
new: to owner = "IT Zentrum"

where supply category = "IT/Software"

Responsible department does not change.

apprx 3000 items

**Comment by nimaai** [comment]
@nadjaweisskopf just to be sure, proper names of the pools are they are in the DB are:
old: "ZHdK-Inventar"
new: "IT-Zentrum"

and the supply category: "IC-Technik/Software"

**Comment by nimaai** [comment]
@nadjaweisskopf retired items **should not** be moved, right?

**Comment by nadjaweisskopf** [comment]
Please move ALL items, even the ones which are retired. I discussed this with B. Flaad this morning. 
Exactly, the pools are ZHdK-Inventar, IT-Zentrum and the category in German is IC-Technik/Software (English IT/Software)
Thanks!

**Comment by nimaai** [comment]
@nadjaweisskopf script deployed and executed on TEST. out of 5799 items 1 could not be moved, because of the following error message: `error for INV4491: Validation failed: The item cannot be retired because it's not returned yet or has already been assigned to a contract line.`. it's a strange item: retired, not borrowable, but still lended currently. i suppose they will have to deal with this item manually, ok?

**Comment by nadjaweisskopf** [comment]
yes, no problem. If it is just one item they can solve this manually. I'll inform them.

**Comment by nimaai** [comment]
items moved on PROD:
```
Items owned by ZHdK-Inventar BEFORE: 18176
Items owned by IT-Zentrum BEFORE: 443
number of items to move: 5799
error for INV4491: Validation failed: The item cannot be retired because it's not returned yet or has already been assigned to a contract line.
Items owned by ZHdK-Inventar AFTER: 12378
Items owned by IT-Zentrum AFTER: 6241
```
