### ISSUE TITLE
Borrow: optimize menu section and user settings

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1621]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**
The user menu and the section menu in borrow is not well designed. With growing amount of registered inventory pools, the button design for each inventory pool is confusion.

---

#### Section menu
- in Top-Dropdown, use Label "Bereich" and selected section Name highlighted
- left-align titles
- Change buttons to `<select>` menu

#### User settings menu
- Remove Name (Sur- and Lastname) in Menu
- Change buttons to `<select>` menu
- minimize Logout button

![Image](https://github.com/leihs/leihs/assets/123965725/df3b3b84-5b7e-460e-81b2-694e40dc50df)
![Image](https://github.com/leihs/leihs/assets/123965725/8ee468f9-01f4-4ed5-a738-87afdf1008e2)

**Comment by belafonte** [comment]
Looks much cleaner to me.

The down chevron at Ausleihen seems a little misleading.
In my case it is not a Dropdown but opens the sheet.

The "sheet" could also be animated a bit  ;)
https://ui.shadcn.com/docs/components/sheet

**Comment by neoheat** [comment]
@belafonte true, the down chevron icon is a bit misleading. As an alternative, we could consider to use a menu dropdown instead of a "sheet" at the position of the menu. Because the users only have one interaction (select an option of a select field or klick of a button) within the menu, this might work as well. With the minimized space when using select fields, we shoudn't have issues with mobile view either.

**Comment by urs-van-binsbergen** [comment]
What we have now is just a relict of the mobile version, it's quite ugly, I know. 

Section menu: I would not introduce select list nested in a menu, but instead optimize the flyout so that the menu itself acts like a select list: 
- flyout compact just below the button instead of a drawer from the right (like in legacy and also admin/procure)
- menu contents with a leaner design similar to the category navigation (no buttons)
- maybe we should introduce the same icons like in legacy/admin/procure to harmonize this menu? 

User menu
- Here I agree with the select lists for language and profile selection and I like the proposed design in general
- In the screenshot the link to the user profile is missing (and is not easy to fit into this design)
- Maybe better to separate-out the language menu (like in admin/procure)? Then it could also be a normal flyout menu.

**Comment by neoheat** [comment]
@urs-van-binsbergen 
Here are two more suggestions based on your comments

<img width="750" alt="Bereich-Menu" src="https://github.com/leihs/leihs/assets/123965725/430fa599-044a-4b73-954c-64ea11df2d12">
<img width="750" alt="User-Menu" src="https://github.com/leihs/leihs/assets/123965725/6c2a38ed-008d-4e2c-bc1c-0e4ee8064b05">

**Comment by urs-van-binsbergen** [comment]
6859cab7883209d7bc23907b81257402a3e0d687

**Comment by neoheat** [comment]
tested positive
