### ISSUE TITLE
procure: use next.jdbc and honeysql2

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1626]
- https://github.com/seancorfield/next-jdbc
- https://github.com/seancorfield/honeysql

**Comment by SeduroDotCom** [comment]
PR's
1. https://github.com/leihs/leihs-procure/pull/125
2. https://github.com/leihs/leihs/pull/1640

**Comment by neoheat** [comment]
Hi @SeduroDotCom 
While testing, I found two issues with the change to next.jdbc and honeysql2

1. The images of the categories are not displayed -> Probably same issue as in borrow (Cast UUID)
2. When adding a new request, the following error appears:

`Error :(

ApolloError: class java.lang.String cannot be cast to class clojure.lang.IObj (java.lang.String is in module java.base of loader 'bootstrap'; clojure.lang.IObj is in unnamed module of loader 'app')
API-Fehler-Details:
[
  {
    "message": "class java.lang.String cannot be cast to class clojure.lang.IObj (java.lang.String is in module java.base of loader 'bootstrap'; clojure.lang.IObj is in unnamed module of loader 'app')",
    "locations": [
      {
        "line": 173,
        "column": 5
      }
    ],
    "path": [
      "requests",
      0,
      "attachments",
      "value"
    ],
    "extensions": {
      "exception": "ClassCastException"
    }
  }
]`

thx for fixing, then I can do further testing.

**Comment by SeduroDotCom** [comment]
Fixed version is now available on https://test.leihs.zhdk.ch/procure/requests

PR: https://github.com/leihs/leihs-procure/pull/127

![image-icon-test-ok](https://github.com/leihs/leihs/assets/32426621/2e667244-74e6-487c-b316-63ca77aa2dac)

**Comment by SeduroDotCom** [comment]
FYI: PR's bellow contains following improvements/fixes
1. Data cleanup of procurement_attachments.metadata (completely in json now)
2. Fixes & tests regarding uuid-cast, "fetchCreatedRequest"
3. Prefer fetching of single request if possible instead of fetchAllRequests

In more detail, see:
1. Data cleanup of procurement_attachments.metadata by migration-script.
https://github.com/leihs/leihs_database/pull/22/files
4. Fixes regarding attachment-fetch, fetch-of-created-request
https://github.com/leihs/leihs-procure/pull/128/files

**Comment by neoheat** [comment]
tested positive
