### ISSUE TITLE
Illegal handover with barcode scanner

### ISSUE THREAD

**Issue by HoMeMartin** [leihs/leihs#1628]
**Application**
lending

**Describe the bug**
During handover, a non-booked item can be issued with the barcode reader. 
The bug is that items can also be issued that are actually already reserved for someone else.

**To Reproduce**

1. Start a Handover 
2. Using a barcode reader or manually entering a barcode for an item that someone else has borrowed
3. leihs does not check that there are now too few items in the loan (the student has now snatched the item away)

Example:
======

Inventory:
  1x 4K camera
  9x HD camera
----------------------------------

Booking:
 Student 1 (Max Mustermann)
  books 1x 4K camera
  for Tuesday to Wednesday

 Student 2 (Lady Bug)
  books 1x HD camera
  for Monday to Friday
----------------------------------

Handover:
 Student 2 (Lady Bug)
  comes to the lending desk on Monday and says she accidentally booked the wrong camera.
  She actually wants the 4K camera

  The employee deletes the incorrectly booked camera and 
  reads the 4K camera with the barcode scanner.
  (Bug: This action should be prevented by leihs because the camera was booked for student 1)

  Student 1 (Max Musterman)
   comes to the circulation desk on Tuesday and wants to pick up his booked 4K camera
   The employee cannot find the camera and sees in the system that it has already been issued.

   The employee says sorry and the student leaves, exasperated ;-P

**Expected behavior**
leihs should check whether the item is no longer available in sufficient quantities when scanning a barcode.
If this is the case, leihs must issue a message that the item cannot be issued because another user has already booked it.

**Desktop (please complete the following information):**
leihs Version 7.2.0

Many thanks for your time and best regards 
Martin Weber

**Comment by neoheat** [comment]
Dear @HoMeMartin 

I tried to reproduce your behaviour, but there are several hints that show me that there is no availiabilty of an item in handover.

### My test setup:

User 1 orders a item **Aktivlautsprecher Eclipse E**


User 2 orders item **Aktivlautsprecher Fostex 6301B** 
<img width="1117" alt="original order of User 2" src="https://github.com/leihs/leihs/assets/123965725/afc2adb2-b71e-4a05-97c2-2260c0bb6e7a">


both orders are approved by the lender


### Handout

1. User 2 arrives at the desk and decide to change the model from **Aktivlautsprecher Fostex 6301B** to **Aktivlautsprecher Eclipse E**. 
2. The lender has now several options to change the model:
a) The lender uses the field "Hinzufügen/Zuweisen" to select the other model "**Aktivlautsprecher Eclipse E**". --> in the dropdown, the lender gets a hint that there is no availability because of the reservation of 
<img width="1007" alt="1st clue of no availability" src="https://github.com/leihs/leihs/assets/123965725/668a0c07-8030-4a8b-bf62-69360c1b6575">

b) the lender choosed the option "Modell tauschen" and searches for  "Aktivlautsprecher Eclipse E"--> the lender gets a hint (greyed out) that there is no availability of this model. Despite that, the button "Auswählen" can be clicked!
<img width="1168" alt="change modell" src="https://github.com/leihs/leihs/assets/123965725/fc1dcd6b-10f1-4c47-8219-32069aa7d24d">

c) the lender scans the barcode of an item. If this item is reserved, a red bar on the left and an red note in the row shows, that there is a conflict.
![Uploading Item scanned that has a reservation.png…]()


### Conclusion:
the lender has several possibilities to see that there is no availability. In the timeline of the model, the availability can be checked too.
<img width="438" alt="timeline" src="https://github.com/leihs/leihs/assets/123965725/5411d2f8-28c6-49d1-81a5-0eb55db99263">
<img width="1020" alt="2nd Clue of no availability" src="https://github.com/leihs/leihs/assets/123965725/a37b1186-9378-49e8-8ac4-939ea43320ad">


**But one important note:**
We never prevent a handout of a reserved item. This is not a bug, it's an intended behaviour.


I hope my feedback is helpful,
best regard, Lukas

**Comment by HoMeMartin** [comment]
> c) the lender scans the barcode of an item. If this item is reserved, a red bar on the left and an red note in the row shows, that there is a conflict.

> But one important note:
We never prevent a handout of a reserved item. This is not a bug, it's an intended behaviour.

Oh god I overlooked the red bar and the red notitz.

Thank you very much for your detailed answer.
So it is a typical OSI layer 8 problem (°~°).

So there is no bug and the case is solved.
