### ISSUE TITLE
admin: no access to `/admin` with firefox browsers on test servers

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1750]
**Application**
admin

**Describe the bug**
Accessing `/admin` in Firefox is not possible. The behavior is not consistent, in https://test.leihs.zhdk.ch works for me, in https://staging.leihs.zhdk.ch not. It clearly has to be an issue with the basic auth protection on test & staging servers. Though app `borrow` is accessible.

**To Reproduce**
1. open firefox
2. navigation to https://staging.leihs.zhdk.ch/admin
3. Login with AAD
4. Page is not loading (network analysis said: 401 unauthorized)

**Expected behavior**
Access to /admin works in every browser, on production as on test servers

**Screenshots**

**Desktop (please complete the following information):**
- Device: Desktop
- OS & Version: MacOS 14.5
- Browser & Version: Firefox 115.12.0

**Comment by DrTom** [comment]
Confirmed with recent Firefox versions >= 125. 

Cause: "Basic Auth" secret handling seems to have changed in Firefox. 

After successful authorization there is a redirect to `/admin` going on which is not visible in the UI of Firefox. Firefox sends the previous entered "Basic Auth" credentials to `/admin` which as we know do not work there and `/admin` responses with an 401 (which is correct). 

Now, at this point all the other tested browsers would delete the invalid "Basic  Auth" credentials; `/admin` will work then and when switch back to `/` or `/manage` we will have to supply the "Basic Auth" Credentials again (because they have been purged). 

Firefox does not (anymore) delete the invalid "Basic Auth" credentials and just seems to hang. `/admin` is effectively not accessible anymore via Firefox. One can switch to `/manage`, that works immediately which confirms that the previously entered "Basic Auth" credentials are sill active.

**Comment by DrTom** [comment]
https://github.com/leihs/leihs/issues/1754
