### ISSUE TITLE
Procurement: Error in procurement request

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1776]
**Application**
`procurement`

**Describe the bug**
An error is displayed in the procurement request `2025.041` in https://leihs.zhdk.ch/procure/requests

`[
  {
    "message": "",
    "locations": [
      {
        "line": 173,
        "column": 5
      }
    ],
    "path": [
      "requests",
      0,
      "attachments",
      "value"
    ],
    "extensions": {
      "exception": "NullPointerException"
    }
  }
]`

**To Reproduce**
1. Go to https://leihs.zhdk.ch/procure/requests
2. search for request `2025.041`
3. see error

**Expected behavior**
The request detail with the appropriate attachment is visible 

**Screenshots**

![Image](https://github.com/user-attachments/assets/fc48c562-dbc6-41aa-83ff-9d5deda0d4ea)

**Leihs version**
7.6.1

**Desktop (please complete the following information):**
- Device: Desktop
- OS & Version: all
- Browser & Version all

**Additional context**
> Add any other context about the problem here.

**Comment by neoheat** [comment]
attachement to analyse in https://service.itz.zhdk.ch/otrs/index.pl?Action=AgentTicketZoom;TicketID=525298

**Comment by nimaai** [comment]
the data for this attachment is empty in the `attachments` table. so is it for one another attachment:
```
-[ RECORD 1 ]----+-------------------------------------
id               | 0e727359-e900-450f-a634-2ecc284db227
request_id       | e54021ff-db4a-47e5-88f3-d9f1d62bfa50
filename         | 
content_type     | 
size             | 
content          | 
metadata         | []
exiftool_version | 
exiftool_options | 
-[ RECORD 2 ]----+-------------------------------------
id               | fe870fd9-6690-479d-8390-abb4eab0ef1a
request_id       | b85572d3-b7cd-48e2-9e91-01ec679ab78c
filename         | 
content_type     | 
size             | 
content          | 
metadata         | null
exiftool_version | 
exiftool_options | 
```
i would delete this two rows so that the error goes away. one would need to upload the attachments again to fix this particular issue.

to analyze how this could happen needs to be done. my first guess would be some disruption during upload. we have a specific procedure implemented in procure.

**Comment by neoheat** [comment]
@nimaai  👍 just delete that in the db, i'll try to upload again. I have the zip for the attachment.

**Comment by nimaai** [comment]
@neoheat done on prod. try to upload again.

**Comment by nimaai** [comment]
identified problems so far:
1. there are some stale uploads in the DB. most probably they come due to the following: if one attaches a new file to the request and deletes it before clicking on "save", such an upload isn't deleted from DB.
2. all the relevant DB columns in `procurement_attachments` are `NULL`able unlike in the `procurement_uploads` table. it is better to make them `NOT NULL`able to prevent a `NullPointerException` in future. in such a case, the upload of the file (attaching it to the request form) would file. this is better as it is a debuggable source if for some reasons it should fail in a particular case.

**Comment by nimaai** [comment]
1. all stale uploads older than 6 months are now deleted after an `INSERT` in `procurement_uploads` table
2. all missing constraints added in all 3 tables

https://github.com/leihs/leihs/commit/3c5e20d59957733b0120554aea4cd873583668a2

**Comment by neoheat** [comment]
hi @nimaai 
another issue in PROD https://service.itz.zhdk.ch/otrs/index.pl?Action=AgentTicketZoom;TicketID=529152. Could you please delete this attachment

**Comment by nimaai** [comment]
Same problem as original, because my fix hasn't been deployed yet. It came after `7.7.0` and it's not in the latest `7.7.1` either (which hasn't been deployed yet).

**Comment by nimaai** [comment]
broken attachment deleted
