### ISSUE TITLE
adding an item is case sensitive 

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#211]
1. go to pool it-zentrum
2. open a hand over
3. add "inv38260"
4. adding this item only works, if you type "INV38260"

**Comment by nimaai** [comment]
2 functionalities of the input field on the hand over page are to be considered:
1. Searching after a model. Right now it is not possible to find a model using the inventory code of one of its items. That would be a new feature (or change request). In such a case one may disregard the case (upper/lower) of the inventory code in order to find the model.
2. Assigning an item or/and adding the respective reservation line. Here one has to pose oneself a fundamental question: should "inv1234" and "INV1234" be considered the same codes resp. the same items? Because right now they aren't. If we disregard the case sensitivity of the inventory codes and assign "inv1234" which item do we mean resp. which item should be assigned: "inv1234" or "INV1234" ?

**Comment by nadjaweisskopf** [comment]
To be changed: 

1. when saving the item or sw, then the item nr. is saved in capital letters
2. Find out, why it is not possible to save two items with the same item nr., one in capital letters, one in small letters. 
3. Assign-field in hand over should not be case sentitive when adding by typing the inventory code

**Comment by nimaai** [comment]
@nadjaweisskopf And what about the options? Their inventory codes are mainly stored in lowercase... I am not sure we want to store them always in uppercase, but on the other hand we should do it consistently in regards to the items.

Actually, I think we should do the following:
1. Save inventory code **AS PROVIDED** by the user (lowercase or uppercase).
2. Saving "inv123" should not be possible if "INV123" already exists. Same for vice-versa.
3. Assigning "inv123" will find and assign "inv123" **OR** "INV123" depending on which one of the two exists (they can't exist both). The same for assigning "INV123".

**Comment by nadjaweisskopf** [comment]
Yes ok. I think this is the situation we already have in production. Then let's develop as you proposed.
