### ISSUE TITLE
Change sorting order in search overview

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#242]
Needed sort order as following:

1. contracts of users which are open - sorted according 
2. contracts of users which are closed - sorted according to there "closing date"
3. contracts of delegations which are open
4. contracts of delegations which are closed - sorted according to there "closing date"

Adding sorting-order-dropdowns to the page: 
1. status ASC / status DESC
2. alpha ASC / alpha DESC / close date ASC /  close date DESC

Nadja: Ask Roger

**Comment by nadjaweisskopf** [comment]
Sorting criterias:

1. status: open first
2. user type (user/deleg.) users first
3. closed date: desc
4. alphabetic: asc

for search overview and contracts page
default setting and filter menu for user to chose the order (n contracts page)

**Comment by nimaai** [comment]
Right now we don't have something like "closed date" (for closed) and "take back date" (for signed) of a contract. We have only "end date" for a particular reservation line and the end dates of such individual lines may differ. Moreover we have also "returned date" on an individual line, which may also differ.

In case of signed contracts, the "take back date" could be considered either the minimum or the maximum "end date" (the earliest or the latest) of all its reservation lines.

In case of closed contracts one could consider "closed date" of a contract the "returned date" of the last item returned (which may be different from its original "end date"). Then and only then is the contract "closed", actually. Otherwise one would need to do something similar with "end date" as in the case of signed contracts (explained further above).

Doing the dynamic computation and sorting of these dates (on the basis of "end date") on top of our present suboptimal implementation would complicate the situation further and further and would make it slower. I pledge against it and suggest to take up this ticket once the refactoring of orders/contracts/reservations is done. This refactoring would namely most probably also include precisely specifying and persisting more information in DB, among others the above mentioned "closed date" and possible the "take back date" too.

**Comment by nadjaweisskopf** [comment]
Nadja: Ask Roger, if we can use the created date of the contract as sorting criteria.

**Comment by nadjaweisskopf** [comment]
No - created date is not an option.

**Comment by nadjaweisskopf** [comment]
@nimaai Matus, we will visit Roger tomorrow afternoon to discuss this ticket.

**Comment by nimaai** [comment]
@nadjaweisskopf Before the commit "Global search users and delegations contracts" (https://github.com/leihs/leihs_legacy/commit/bde10c8a1eb8fa7f777c3065b36f89408e4febb5) the sorting of the closed contracts was `created_at DESC` -> https://github.com/leihs/leihs_legacy/commit/bde10c8a1eb8fa7f777c3065b36f89408e4febb5#diff-0e052982891b1836f2f404d8406bd0eaL263.

**Comment by nimaai** [comment]
@nadjaweisskopf I implement it as discussed last time with you:

> Bei den offenen ändert sich nichts. Aber die geschlossenen werden nach created_at Datum sortiert, sonst nichts.

**Comment by nimaai** [comment]
@nadjaweisskopf I have just realised that the "created at" before the above mentioned commit was even wrong! The supposedly "created at" was actually the date of the latest reserved line of the particular contract, means `MAX(reservations.created_at)`. I will change it accordingly, so that "contracts.created_at" means what it should.

 > I hope we can close this ticket for good after this change.

We can maybe close this ticket then, but this story is far from over. Current implementation is simply crazy.
