### ISSUE TITLE
Use a delegation in inventory manager

### ISSUE THREAD

**Issue by Oreonax** [leihs/leihs#271]
We try to use a delegation as an inventory manager but the people inside the delegation aren't granted with the new right after that. Adding them manually with their name works.

#### Specifications
- Leihs version: 4.3.1
- MySQL/PostreSQL version: 9.6

**Comment by nadjaweisskopf** [comment]
The concept of delegations is only used for lending items. It is not intended to use the delegation to grant priveleges. We are planning to remodel the delegations-concept and build "real" groups, instead of using the "user-concept". Therefor I will close this ticket. Granting priveleges to delegations will not be implemented in near future.
