### ISSUE TITLE
Error when adding an inventory mgr.

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#283]
#### Expected behaviour
It should be possible to add an inventory mgr. in Admin-section to the pool "Master Fine Arts"

#### Actual behaviour
When adding an inventory mgr. "Honegger Mike" than I get an error "Sorry, but something went wrong..."

#### Steps to reproduce
time: 16.10 - 2.8.
1. Go to pool "Master Fine Arts" in Admin section
2. Add Mike Honegger as Inventory Mgr.
3. Save
4. Error

Another pool where this error is shown: "Vertiefung visuelle Kommunikation" 

![error msg deactivate pool](https://user-images.githubusercontent.com/3356016/28878676-3db1098e-77a0-11e7-911d-cfc49c787e42.png)

**Comment by nadjaweisskopf** [comment]
Pool "Master Fine arts" can not be edited in Admin section. These problems might be connected.

**Comment by eins78** [comment]
@nimaai 

```
Aug 29 08:59:30 zhdk-leihs-staging ruby[58917]: ActionView::Template::Error (comparison of User with User failed):
Aug 29 08:59:30 zhdk-leihs-staging ruby[58917]: 77:           result.firstname + ' ' + result.lastname
Aug 29 08:59:30 zhdk-leihs-staging ruby[58917]: 78:         else
Aug 29 08:59:30 zhdk-leihs-staging ruby[58917]: 79:           result.text
Aug 29 08:59:30 zhdk-leihs-staging ruby[58917]: 80:     #{@inventory_pool.users.inventory_managers.sort{|a,b| a.lastname <=> b.lastname}.to_json(only: [:id, :firstname, :lastname])}.forEach (user, i)->
Aug 29 08:59:30 zhdk-leihs-staging ruby[58917]: 81:       option = new Option(user.firstname + ' ' + user.lastname, user.id, true, true)
Aug 29 08:59:30 zhdk-leihs-staging ruby[58917]: 82:       element.append(option)
Aug 29 08:59:30 zhdk-leihs-staging ruby[58917]: 83:     element.trigger('change')
Aug 29 08:59:30 zhdk-leihs-staging ruby[58917]: engines/leihs_admin/app/views/leihs_admin/inventory_pools/_form.html.haml:80:in `sort'
Aug 29 08:59:30 zhdk-leihs-staging ruby[58917]: engines/leihs_admin/app/views/leihs_admin/inventory_pools/_form.html.haml:80:in `_engines_leihs_admin_app_views_leihs_admin_inventory_pools__form_html_haml___2973
```

https://github.com/leihs/leihs_legacy/blob/8f5e861aa3f830b4fb38e5163ba740562d5c6de0/engines/leihs_admin/app/views/leihs_admin/inventory_pools/_form.html.haml#L80

**Comment by eins78** [comment]
cause of bug:
- users in admin list are sorted by lastname, in a way that breaks when `lastname=NULL`
- some users have `lastname=NULL` (in practice those are delegations that only have a `firstname`)

simple fix: sort in a way that does not crash (AR `order` instead of ruby `sort`)

**Comment by nadjaweisskopf** [comment]
In addition we have the following problem: 

When a user logs in to leihs and his pool has been deactivated, he gets an error. If he uses the alternative login (leihs.zhdk.ch/borrow) or (ausleihe.zhdk.ch/borrow) then the login works.

**Comment by eins78** [comment]
we have solved 2 bugs, waiting for CI.

- pool "Master Fine Arts" could not be edited because of the `lastname=NULL` problem i mentioned 
- login problem: Users with admin rights for only inactive pools were redirected to /admin, but since there is no active pool to show it crashed. We changed the model scope for access rights – if they point to an inactive inventory pool, they are also regarded 'not active'.

**Comment by eins78** [comment]
@nimaai @nadjaweisskopf actual problem that causes the bug in this ticket is now found, but I am not sure what is the correct way of solving it.

why does it crash in this case? because the user had an `access_right` for this pool in the past (with `deleted_at=…`). when user is added again as admin, backend tries to create a new `access_right`, which fails because user&pool have to be *unique* (constraint).

the most easy solution would be re-use that previous `access_right`. we loose the information when it was previously "deleted" – is that important?

**Comment by nadjaweisskopf** [comment]
@eins78 And why don't we delete the access_right when the user is removed from the pool? Would't that be correct?

**Comment by nimaai** [comment]
> the most easy solution would be re-use that previous access_right. 

We should, but we don't: https://github.com/leihs/leihs_legacy/blob/3adc9a4369af8995aa532b46b51db94aa0c5dc34/app/controllers/manage/users_controller.rb#L146
It is a bug; this line should be removed. According to my analysis, there is not a single access right in the DB with `role = 'no_access'`.

> we loose the information when it was previously "deleted" – is that important?

No. I am not aware of any use case where this date plays a role... @psy-q ?

> And why don't we delete the access_right when the user is removed from the pool? Would't that be correct?

That's a very good question. Roughly, because of old contracts and stuff for users who had at some point of time access to a specific pool...
