### ISSUE TITLE
SW: don't show building and room on software-list

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#298]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
First see github.com/leihs/leihs/wiki and relishapp.com/leihs. Then provide a short but meaningful description of the expected behaviour.

#### Actual behaviour
Provide a short but meaningful description of the actual behaviour.

#### Steps to reproduce
Please include the role of the logged in user as well as precise steps starting with logging in upto the occurence of the problem.

#### Related issues
If you have found some already existing issue(s) which this one relates to, then you can mention it (them) here.

#### Specifications
- Leihs version:
- Browser version:
- MySQL/PostreSQL version:

**Comment by eins78** [comment]
I checked all the views in inventory that show Software/Licenses. It seems to be displayed only in the index/table list.

- edit software: no building/room field
- edit license: no building/room field
- table: see screenshot

basially:

- [ ] In the Inventory list, don't show Building/Room field info if it is Software or License

![screen shot 2017-09-01 at 12 03 43](https://user-images.githubusercontent.com/134942/29965642-bc259b38-8f0e-11e7-8963-5a66d52682ad.png)

**Comment by eins78** [comment]
bonus fix: it turned out the last "Undefined" in the screenshot above did not came from the Location info but was an UI bug with show `undefined` license type as such.

note that the general "location" is still shown (inventory pool, and person if currently borrowed – that looked rather important).

![screen shot 2017-09-01 at 15 00 47](https://user-images.githubusercontent.com/134942/29973636-9060a246-8f30-11e7-97fe-54903a8cd4ff.png)
