### ISSUE TITLE
SW: implement new field on software license: version

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#299]

**Comment by eins78** [comment]
current UI software & licence:

![screen shot 2017-09-04 at 17 26 02](https://user-images.githubusercontent.com/134942/30032819-33594b24-9198-11e7-8145-dd85ec8ac63f.png)

![screen shot 2017-09-04 at 17 26 40](https://user-images.githubusercontent.com/134942/30032808-2c08f658-9198-11e7-8390-5d1886ab3e56.png)

---

proposal new UI for license. 

- explicit label
- show version from software as well to minimize errors (versions can be added in both places and technically we can't know if it's correct, so we show it)

![screen shot 2017-09-04 at 17 39 56](https://user-images.githubusercontent.com/134942/30032833-4320e7c4-9198-11e7-8d61-4af7ec292132.png)

**Comment by nadjaweisskopf** [comment]
@eins78 that makes sence. Let's impement it that way and see what Tilo says when he tests.

**Comment by phiku** [comment]
@eins78 I would propose not to show the Software Version. It would be quite complicated to show, because when you would have to show the Software Version depending on the selection in the Software dropdown. Its not obvious how to do it for me, perhaps through a field dependency. But anyway, if the Software has a version, it is displayed in the Software dropdown, so it is not so important to display it seperately.

**Comment by phiku** [comment]
Done.

**Comment by nadjaweisskopf** [comment]
@phiku We need an additional ticket: the license should be shown in the license list (Inventory list)
test ok for this ticket.
