### ISSUE TITLE
local installation 

### ISSUE THREAD

**Issue by sonoprob** [leihs/leihs#314]
I am reading here [from Matúš Kmiť]:
https://github.com/leihs/leihs/wiki/Deployment

As I'd idealy deploy leihs just on a single VM, we have some 200 users -
and a relatively light organisation with 4 ppl managing rentals.

So, I'm a little stuck with ansible,

[ installing v.4 master branch on fresh debian 9 VM ]

I tried having control machine and managed node be the same (localhost),
though it may not make much sense (indeed I get an error: [1])

• my question:
is it still possible to run it 'just' on localhost, perhaps
with ansible, or could you advice the way to work around it ?

**Comment by eins78** [comment]
@sonoprob re-using the server (VM) as a control machine is not suported, because it does not make sense in practice: The controll machine contains the (ansible) inventory, which in turn contains secrets and other kinds of config that should absolutely not be present on the server.

The error you are seeing is related to ansible internals, but since this kind of setup is not supported we won't work around it.

I suggest you use a local workstation (either Mac-or-Linux-based) or a dedicated Debian VM (could also be on a local workstation, or on a server in a secure network zone – a "bastion" in ansible parlance)

**Comment by nadjaweisskopf** [comment]
@sonoprob please reopen this ticket if your problem persists.
