### ISSUE TITLE
Server für Madek-Hilfe einrichten (Madek)

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#332]

**Comment by nadjaweisskopf** [comment]
@eins78 Do you think the madek-help pages can be finished this Friday (2.2.18)?

**Comment by eins78** [comment]
@nadjaweisskopf Yes, that's likely. I just have to move the webspace from the temporary domain to the real one (currently: http://madek-doku.zhdk.ch). 
The last step would be automating deployment via the CI, but I'll wait until I have feddback/clarity regarding the "split up" between general and zhdk-docs (after the webspace is moved).
Also currently we dont need the automation because there are no changes.

**Comment by nadjaweisskopf** [comment]
@eins78 ok, perfect, thanks. Note for tomorrow: Could you please send Susanne an invitation to discuss the automation and to check the other ticket https://www.pivotaltracker.com/story/show/151290287

**Comment by eins78** [comment]
setup done, only 2 administrative tasks open 

- [x] docs: CI for http://doku.madek.ch/
- [x] docs: CI for https://medienarchiv.zhdk.ch/hilfe/
- [x] Madek: deploy for https://medienarchiv.zhdk.ch/hilfe/
- [ ] Madek admin: set `support_url = //medienarchiv.zhdk.ch/hilfe/` (when ready)
- [ ] Gitbooks: Setup Sync to Github (or give access to max)
