### ISSUE TITLE
Performance-Bug Dyn. Reservations

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#357]
ask Matus!

**Comment by nimaai** [comment]
http://nimaai.ruby.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/orders?state%5B%5D=approved&state%5B%5D=submitted&state%5B%5D=rejected

http://nimaai.ruby.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/contracts?status%5B%5D=open&status%5B%5D=closed

The cause is total count; the query takes long. This count is needed in order for the frontend to be able to prepare the empty pages which are then filled when one is scrolling.

This is our present scrolling setup in leihs used in several places for list views.
