### ISSUE TITLE
pool is not shown in global search (wait for Matus)

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#377]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
I would expect to see to which pool this item belongs. 

#### Actual behaviour
The item is shown without an information about its pool.

#### Steps to reproduce
1. go to pool Ausleihe Toni-Ausleihe
2. search for item AVZ14950 in global search
3. item is listed without pool description

**Comment by phiku** [comment]
@nadjaweisskopf Kann es sein, dass der Grund ist, dass er nicht mehr aktiv ist, der Inventory Pool?

**Comment by nadjaweisskopf** [comment]
@phiku I will check this with Mike. But I assume he would like the item to be displayed but with a "retired" label somewhere on the line.

**Comment by nadjaweisskopf** [comment]
@phiku nadja: check in which pool this item is and why the pool is not shown.

**Comment by eins78** [comment]
@phiku Testfall: Gegenstand, ausgemustert, aus inaktivem Pool: `INV40747`
Was mir noch auffiel: braucht evtl. es Rechte um einen Pool zu sehen?

**Comment by nadjaweisskopf** [comment]
Following behaviour has been discussed with Mike
- Du suchst nach einem Gegenstand in der globalen Suche
- Dieser Gegenstand ist ausgemustert und gehört zu einem bereits ausgemusterten Gerätepark
- Der Gegenstand wird angezeigt aber nur hellgrau - mit dem Vermerk, dass der Gegenstand ausgemustert ist. Der Name des ausgemusterten Geräteparks wird angezeigt.

**Comment by phiku** [comment]
Analysis: 

The controller of the search is: search_overview_controller.coffee
The rendering of the line is: .../manage/views/items/line.jsr.erb

The line uses the following attribute:
  <div class='col2of8 line-col text-align-left padding-right-s'>
    {{>current_location}}
  </div>

The attribute current_location is composed directly in item.rb. The problem is, the inventory_pool is nil in this method. The reason is, the default_scope of inventory_pool is where is_active is true. 

We cannot simply unscope, because inventory_pool in item.rb is defined with belongs_to. We could check, if we load the inventory_pool seperately if the inventory_pool is nil. Of course the default_scope is the main problem. But @nimaai has to decide, if we somehow can take this away or not.

**Comment by phiku** [comment]
Note:

It is not enough to load the inactive inventory pool explicitly in the method current_location (as I thought in the last comment), since in .../manage/items/index.json.haml there is extra logic for current_location. So we have the default scope in the inventory_pool.rb, then we have the logic in item.rb for current_location and at the end we override some stuff in index.json.haml

**Comment by phiku** [comment]
Tried to remove the default scope in the following branch: 
pku_master_remove_inventory_pools_default_scope

Tests which have been made explicitly for the inactive inventory pools are green, however not sure if thats enough.

**Comment by nadjaweisskopf** [comment]
@nimaai we will wait for you

**Comment by phiku** [comment]
@nadjaweisskopf Perhaps you can take me out of this ticket, put it into the backlog, that we can plan it another time.

**Comment by phiku** [comment]
Branch in legacy:
pku_master_remove_inventory_pools_default_scope

**Comment by nimaai** [comment]
Implemented as described in on https://github.com/leihs/leihs/issues/377#issuecomment-342435047
