### ISSUE TITLE
Rename field in item: User/Typical usage --> Typical usage / Verwendung

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#396]

**Comment by nimaai** [comment]
@nadjaweisskopf What should be the ID of the field? Right now it is `user_name` which does not fit to the new label anymore.

**Comment by nadjaweisskopf** [comment]
@nimaai can we rename it to "usage"?

**Comment by nimaai** [comment]
Yes, we can. Only for ZHdK, right?

**Comment by nadjaweisskopf** [comment]
@nimaai Can we rename it only for ZHdK? How does that work? If we have more development work or it makes future development more complicated, then we rename the field with ID "usage" for all other leihs-customers too.

**Comment by phiku** [comment]
It seems that something crashed here, because it is stored as JSON String in the DB instead of just JSON Hash.
![bildschirmfoto 2017-11-21 um 08 18 59](https://user-images.githubusercontent.com/16756048/33059489-b3865f92-ce94-11e7-9ab1-361dafc8ab20.png)

**Comment by nadjaweisskopf** [comment]
try to fix the existing problem and copy data from old field to new field. Otherwise revert the whole ticket.

**Comment by phiku** [comment]
Summary of Analysis:
- We reverted this, because the inventory helper crashed. 
- The reason was, that the field data was stored as string, instead of as a hash (most likely just remove .to_json). Therefore the role could not be read from the field data, which caused a nil error. 
- The personas dump commited in git most likely was created before adding .to_json, because when restoring the personas, everything looked fine in Postico. However, when checking out a commit before and then restoring the personas, and then running the migration, caused the same error. 
- An open question is, does the data in item.user_name really have to be dropped, because it is not copied to item.usage. 
- I would remove the down migration, because otherwise one must make sure, that this one also works correctly. Its better to restore to the old personas to try if the up migration works.
