### ISSUE TITLE
When entering decimal numbers then mark field red and show an error

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#411]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
If a decimal price is entered and the user saves then I would expect to see an error msg. saying "Only enter integer numbers" / "Bitte nur ganze Zahlen eingeben".

#### Actual behaviour
The request is not saved and the user has no idea why. 

#### Steps to reproduce
1. go to procurement
2. create a new request
3. enter 200.50 in the price field
4. save the request

#### Specifications
- Leihs version: 4.7.3
- Browser version: safari 11.0
- MySQL/PostreSQL version:

**Comment by eins78** [comment]
Validation was already happening (HTML form "constraint validation"), but maybe it did not work in some browsers. Added `step=1` to make whole numbers explicit, and customized the error message as given in ticket.

Needs thorough testing in multiple browsers – my system is in US locale so it might behave differently in regards to number formats etc (think: `2.5` vs `2,5`)

**Comment by nadjaweisskopf** [comment]
@eins78 when a comma is entered, the field turns red immediately. When a point is entered, the field does not turn red until the user types a number. Can we change the field colour to red as soon as a point or comma is entered? If this is too much effort, then please leave it as it is now on staging!

**Comment by eins78** [comment]
@nadjaweisskopf 

- The pop-up message was supposed to be implemented like you described, but it only worked for the "inline edit". I fixed it, now it also works when adding a new request, and when editing all requests for a user (old view).

- 'comma vs point': This behaviour is dictated by the browser. For example, Chrome does not let me enter a Komma at all (because my system is english and Komma is never valid – for your german system Chrome should forbid entering any points. In my testing it is consistent: `300,00` is also a whole number (in german) and therefore allowed.
In any case, working around it will cause other problems.

I will update the ticket when fix is on staging
