### ISSUE TITLE
Documents in borrow section shows error

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#428]
#### Expected behaviour
I would expect to see the information accordint to the scenarios in "Feature: User documents".

#### Actual behaviour
When accessing the documents I get an error

#### Steps to reproduce
1. go to borrow section
2. access the documents under your name
3. error

#### Specifications
- Leihs version: 4.8.0
- Browser version: safari 11.0

![image002-2](https://user-images.githubusercontent.com/3356016/33019875-6c02ab0a-cdfc-11e7-938e-e0b054ab4e10.png)

**Comment by nadjaweisskopf** [comment]
if this has to do with the default scope of the pools then wait for matus.

**Comment by nadjaweisskopf** [comment]
@phiku test with my user or with Maxs user

**Comment by phiku** [comment]
I used the Gerätepark Modellbau, created an Order, Picked it up, Brought it back, have seen the entry in Documents, retired the items. The documents were still visible. I disabled the Gerätepark Modellbau, the documents crashed. I enabled the Gerätepark Modellbau, the documents were ok again. So its about inactive Geräteparks. 

@nadjaweisskopf What should I do with this ticket now, the analysis is done, we will wait for Matus.

**Comment by nadjaweisskopf** [comment]
@phiku The documents should be visible no matter if the pools are visible or not. Would you rather wait for Matus?

**Comment by eins78** [comment]
@nimaai @phiku Once again the `default_scope` on `InventoryPool` is the culprit. It crashes not only this view, but also viewing old contracts (and maybe even more).
I tried adding a scope/lambda to the `belongs_to` macro, but somehow AR does not support "unscoping" there. The only that works in overriding it with a custom method, so that `contract.inventory_pool` works in all instances). 
In we don't get rid of the `default_scope`, this soultion could be applied to other models as well (like `Item`).

https://github.com/leihs/leihs_legacy/blob/56e95477422668c4c022e62f94d26817cceb54ea/app/models/contract.rb#L45-L47
