### ISSUE TITLE
calender only considers amount from general group and therefore shows wrong availability

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#446]
Calender shows 0 / 5 instead of 3 / 5. Calender only shows the amount of items people from the general group can lend. But the calender should show the amount of items from groups the user is assigned to. 

#### Expected behaviour
If 10 lendable items exists, 
all 10 are assigned to a group, 
5 of these 10 are already lent and 
2 are in the current order from a user belonging to this group, 
then 3 are still available for this user. 
Calender and timeline should show the same --> amount 3

#### Actual behaviour
When viewing an order with the assumptions as above, the timeline is correct (amount available 3), the number on the left hand side (2/5) in the edit page of an order is correct , but the calender shows "0" which is not correct.

#### Steps to reproduce
1. go to order which needs to be verified
2. go to a unproblematic line where enough items are available
3. edit this line
4. calender shows 0 instead of the correct amount

#### Specifications
- Leihs version: 4.9.0
- Browser version: safari

**Comment by eins78** [comment]
reproduced in a (new) scenario: https://github.com/leihs/leihs_legacy/blob/mfa/bug_446/spec/features/manage/availability_calendar.feature

**Comment by eins78** [comment]
Tried to compare against old code, as it was suspected it broke because of a recent refactoring – no luck. 
Before the commit ["Orders & contracts refactoring"](https://github.com/leihs/leihs_legacy/commit/7d67b28736bd76c207f431dceee1ab61da5491bb)
it was even more broken before. Almost same behaviour as described, but "the number on the left hand side" shows "1/5".

**Comment by phiku** [comment]
@nadjaweisskopf 
"2 are in the current order from a user belonging to this group,
then 3 are still available for this user.
Calender and timeline should show the same --> amount 3"

Should the calender really show only 3? Or perhaps 5, since 2 are already in the order, but since I edit the order, I can select 5?

**Comment by phiku** [comment]
Available at http://phiku.ruby.zhdk.ch

**Comment by phiku** [comment]
@nadjaweisskopf Delivered to test.

**Comment by nadjaweisskopf** [comment]
@nadja ask Roger if negative numbers are really necessary or if 0 is enough. If retired for example.
