### ISSUE TITLE
Correct text "inspection" in take back

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#452]
![bildschirmfoto 2017-12-05 um 09 13 21](https://user-images.githubusercontent.com/3356016/33596663-b8569560-d99c-11e7-899e-2d838cbd4d4e.png)

#### Specifications
- Leihs version: 4.9.0
- Browser version: safari 11.0

**Comment by eins78** [comment]
take back, template for line of type Software: remove the 'inspect' button and action

**Comment by phiku** [comment]
Do not show the button for software.

**Comment by phiku** [comment]
@nadjaweisskopf Wie kann ich eine Software ausleihen?

**Comment by phiku** [comment]
Analysis:

The error is in the backend rendering:
.../reservations/take_back_line/_item_line.html.haml

The Javascript part is working: 
.../reservations/take_back_line/_item_line.jsr.erb

Normally you therefore do not see the error. If you turn off Javascript, the Dropdown anyway does not open. The erroneous label was only visible on Staging, since there was a real Javasript Error (about Model not found or something like that). The JS Error caused the .jsr.erb not being executed. 

Now of course the backend rendering can be fixed easily. However, i have not found yet, how to decide if its a License or an Item. So I would propose to just fix the Label (which anyway is actually never visible) and leave it for Software too, since it works (perhaps just does not make sense).

**Comment by phiku** [comment]
Implemented the easy way so far.

**Comment by nadjaweisskopf** [comment]
@phiku Some fields of the inspection do not exist for sw-licenses. If nothing breaks, then let's implement as you proposed - just showing the icon correct but keeping the popup. Then we'll see with Matus, how we can solve this for sw-licenses.
