### ISSUE TITLE
possibility to scroll user list

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#460]
#### Expected behaviour
When I enter a user name in the user field, I need to have a scrollable list.

#### Actual behaviour
The list only shows the first five users - not more. 

#### Steps to reproduce
1. go to manage section of a pool
2. go to groups
3. edit a group
4. type a user name, for example "nadja weisskopf"

#### Specifications
- Leihs version: 4.9.0
- Browser version: safari 11.0

<img width="1060" alt="bildschirmfoto 2017-12-11 um 09 53 12" src="https://user-images.githubusercontent.com/3356016/33822817-36bc3e62-de59-11e7-84c9-272d5348e479.png">

**Comment by nimaai** [comment]
@nadjaweisskopf currently the result set of the search is restricted to 5, that's why there is no need to scroll as it is small. to what value should I increase it? default is normally 20. that should be enough if one enters sufficient amount of characters of the searched user.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/c4df7dd0bb95c83137f8bffe1c214c4e1a29c996

**Comment by nimaai** [comment]
I have set the limit to 20; it is our application default on various pages.

**Comment by nadjaweisskopf** [comment]
@nimaai Showing 20 users is ok, that suits well. But when typing a name into the user search field, the typing is really slow. I can reproduce this behaviour only in this search field. Could you please have a look at this? Has anything been changed apart from the amount of listed users?

**Comment by nimaai** [comment]
It is only a problem with safari. @eins78 could you maybe take a look at it?

**Comment by eins78** [comment]
@nadjaweisskopf @nimaai reproduced
- its a performace problem
- confirmed its only in safari, likely due to their (internal) form handling

We can't really do or fix anything: the problem is not in our JavaScript code (in fact, it's still slow if we deactive it in the code or even completely in the browser!).

The cause seems to be that these forms can get really large very quickly. Several hidden input elements are used for each assigned model and user, so the "AV-Services" one has several thousand fields causing Safari to slow down.

proofs ;)
- the 'group name' field is also slow (so its not the search field's code)
- all fields are also slow if JS is disabled in browser
- it is not slow for smaller groups 

Conclusion: Since the slowdown is rather mild, we should ignore it and maybe report to Apple if it gets worse/unusable. We could only solve it by completetly restructuring the way the form is built, not really worth it in my opinion.
