### ISSUE TITLE
fix templates in borrow section

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#500]
Wizard - Write the max. existing in in field

test nadja: retire an item and check msg. if added to a group

**Comment by eins78** [comment]
a) found another bug, "unavailable lines" should be marked red with a block as well. fixed that, because otherwise problematic lines would be hard to find after this change

b) @nadjaweisskopf Maybe the messages should be different? I am not sure if we should mention that unavailable lines have been set to 0 automatically. The rest of the messages is still corrent – decrement numbers if you need less; and contact the pool if you need more.

![screen shot 2018-03-05 at 13 33 12](https://user-images.githubusercontent.com/134942/36975315-01486266-207a-11e8-94b2-44106924e8d7.png)

**Comment by eins78** [comment]
c) also, as we decided for other places in /borrow (like calendar), we won't show negative numbers for availabilty (`0 / 0` instead of `0 / -21`)

**Comment by eins78** [comment]
was fixed in https://github.com/leihs/leihs/commit/6ee5c4b47dc1e60814631278a2969b8a49894cde

**Comment by nadjaweisskopf** [comment]
test ok. We have other problems, which already existed. I will create a ticket for these problems for future iterations.
