### ISSUE TITLE
No longer able to use booking

### ISSUE THREAD

**Issue by mikkelbisgaard** [leihs/leihs#540]
Borrow error: "Booking is no longer possible on this start date"

Added an item to order, Calendar tabs opens and a red frame appears; "Booking is no longer possible on this start date. Booking is no longer possible on this start date." 
However a green window appears on days where the Item is supposed to be in stock and avaliable. But no matter what we do the "Booking is no longer possible"-frame wont go away.

#### Specifications
- Leihs version: Was present in 4.14.1 - updated to 4.16.0-dev still there
- Browser version: Firefox, Chrome
- MySQL/PostreSQL version:PostgreSQL 9.6 

I dont know if it's a setting somewhere or what causes this error message :-/

**Comment by nadjaweisskopf** [comment]
@mikkelbisgaard Unfortunately we introduced a bug in the booking calender. The bug is fixed with 4.16.0 (coming up). Meanwhile please add a max. value either 0 or higher in the manage section of the pool. In 4.16.0, the booking calender does not throw an error if left empty - same behaviour as before 4.14.0. 

<img width="481" alt="bildschirmfoto 2018-03-13 um 11 18 59" src="https://user-images.githubusercontent.com/3356016/37336063-81dbad3e-26b0-11e8-8616-22fbd79007ef.png">
