### ISSUE TITLE
Prio1: Not all status are shown in lending section

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#573]
#### Expected behaviour
I would expect to see following problems
- overdue lines
- defect items
- not lendable items
- not complete items

The behaviour as expected was fine some time ago.

(see printscreen)

#### Actual behaviour
Only overdue lines are shown but other other problems are not mentioned. 

#### Steps to reproduce
1. go to pool Ausleihe Toni-Areal
2. create an order with a model that has four items
 - one item is lendable
 - one item is defect
 - one item is not complete
 - one line is overdue

Only the overdue information is shown.  

#### Specifications
- Leihs version: 4.19.0
- Browser version: safari

<img width="386" alt="bildschirmfoto 2018-05-24 um 09 45 43" src="https://user-images.githubusercontent.com/3356016/40471723-cd8a5748-5f37-11e8-8cf1-08959d69695c.png">

**Comment by eins78** [comment]
@nadjaweisskopf I made a test szenario, but I can not reproduce this. There seems to be at least 1 step missing before "Only the overdue information is shown" – where should it be shown? E.g. where is the screenshot from? I assumed this is the handover page but it looks different.

![screen shot 2018-06-04 at 13 16 15](https://user-images.githubusercontent.com/134942/40914785-d1044c24-67f9-11e8-8f7e-0ef0e00f913d.png)

**Comment by nadjaweisskopf** [comment]
@eins78 we even have scenarios for the problems shown in the printscreen above: 

https://relishapp.com/leihs/main/docs/manage/displaying-problems#showing-problems-in-an-order-when-a-model-is-not-avaiable

**Comment by eins78** [comment]
@nadjaweisskopf Yes those are the scenarios I based the new one on. The existing ones only check 1 problem at a time, I made a new scenario that checks several problems https://github.com/leihs/leihs_legacy/commit/24ca4ad9669792e83922fb88ce772f334d4a2f57

But the problem is that the steps as written can not be followed and/or can't result in the described outcome.
- the steps say there are 4 items, but that would result in 4 lines. If the screenshot shows the hand over screen, than it could be 1 item with 3 problems.
- an overdue item can not be added to an order (validation fails because it is still part of a not-closed contract)

**Comment by eins78** [comment]
@nadjaweisskopf I guess this could be about editing an order. Will try to make a scenario for that case and report back.

**Comment by nadjaweisskopf** [comment]
rewrite ticket above with correct steps - hand over, not order

**Comment by nadjaweisskopf** [comment]
@eins78 I tested all possibilities and did not find a problem. I just informed Roger about the current behaviour: 

**********
Bei den Bestellungen zeigen wir nie Probleme an, da in den Bestellungen keine Inventarcodes zugewiesen werden. 

In den Aushändigungen werden Probleme angezeigt, sobald Inventarnummern zugewiesen werden - egal ob die Modelllinie überfällig ist oder nicht. 

Ich konnte keine Probleme feststellen. Die Printscreens von Dir beinhalten keine Inventarcode-Zuteilungen. Deshalb werden auch keine Probleme angezeigt. 
**********

I will close this ticket.
