### ISSUE TITLE
contract.html.haml - week number is not counted correctly

### ISSUE THREAD

**Issue by DerBachmannRocker** [leihs/leihs#601]
In contract.html.haml I see this:
`%span.weeknumber W#{@contract.created_at.strftime("%U")}`
%U counts week numbers starting with Sunday. See [here](https://apidock.com/ruby/DateTime/strftime).

Therefore, currently contracts show a wrong week number in the title.

It probably should be changed to %W to start counting a new week on Mondays. Or better yet: make it configurable, so the user has a choice about the setting.

> Week number:
The week 1 of YYYY starts with a Sunday or Monday (according to %U
or %W).  The days in the year before the first week are in week 0.
  %U - Week number of the year.  The week starts with Sunday.  (00..53)
  %W - Week number of the year.  The week starts with Monday.  (00..53)

**Comment by nimaai** [comment]
I am not getting it. `@contract.created_at # => Wed, 10 Oct 2018 14:28:41 CEST +02:00` was a wednesday, so this format setting should not have an effect, but it indeed changes in UI from W40 to W41. @eins78 any idea?

**Comment by eins78** [comment]
@nimaai The bug report is correct and it should be changed to `%W` as suggested. We can't really add a setting yet because it would be something like "Weeks start on Sunday or Monday" (as many calendar apps have) and we would have to support it everywhere, including the Calendars in UI.

explanation: The weekday of this date does not matter, but the start of the year does!
2018-01-01 was Monday, so it is one of the years where it makes a difference. If you count weeks starting on sunday, the first such week starts on 2018-01-7.
```ruby
DateTime.parse('2018-01-01').strftime("%W") # => 01
DateTime.parse('2018-01-01').strftime("%U") # => 00
DateTime.parse('2018-01-07').strftime("%U") # => 01
```

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/186ab2e7d0a16ea0472dca0eaf9a49582be0961e
