### ISSUE TITLE
Migration with Ansible to version 4.0.0 has worked but website is not available (Error 503)

### ISSUE THREAD

**Issue by HSLUwem** [leihs/leihs#608]
The migration with Ansible to version 4.0.0 went through without error. When accessing via browser, an Error 503 comes back.
The Apache error log shows that no connection can be made to local port 3210.

What is still missing? What was not set up by Ansible Playbooks?

Apache Error Log:
[leihs_localhost_error.log](https://github.com/leihs/leihs/files/2213598/leihs_localhost_error.log)

Ansible-Output after the successful run:
![leihs400_ansible_output](https://user-images.githubusercontent.com/32535851/42999439-0d137206-8c1e-11e8-9ef1-145c6769a0c7.JPG)

**Comment by lachmannpablo** [comment]
I get a 503 too after successful Ansible deployment. I figured out that /

`etc/systemd/system/leihs.legacy.service`

 does not start up and because of that it's not listening on port 3210. What can we do about it? On our test server it does start up, but I can't figure out the difference.

Thanks and cheers, Pablo

**Comment by lachmannpablo** [comment]
`/home/leihs-legacy/.rubies/ruby-2.4.2/bin/ruby -S /home/leihs-legacy/.rubies/ruby-2.4.2/bin/bundle exec /home/leihs-legacy/.rubies/ruby-2.4.2/bin/puma -e production -t 1:2 -w 4 -b tcp://localhost:3210`
Gives me a:
`Could not locate Gemfile or .bundle/ directory`

**Comment by HSLUwem** [comment]
I can start puma with this command in the directory /leihs/legacy:

/home/leihs-legacy/.rubies/ruby-2.3.3/bin/ruby -S /home/leihs-legacy/.rubies/ruby-2.3.3/bin/bundle exec /home/leihs-legacy/.rubies/ruby-2.3.3/bin/puma -e production -t 1:2 -w 4 -b tcp://localhost:3210

To start the leihs-legacy service i had to create following directory/file:
- mkdir /leihs/legacy/log
- touch /leihs/legacy/scout_apm.log

One problem remains. The service does not start correctly the first time (boot):
Jul 25 07:52:37 as76i systemd[1]: Starting Leihs Legacy Service...
Jul 25 07:52:39 as76i systemd[1]: Started Leihs Legacy Service.
Jul 25 07:52:41 as76i ruby[1514]: [1514] Puma starting in cluster mode...
Jul 25 07:52:41 as76i ruby[1514]: [1514] * Version 3.6.2 (ruby 2.3.3-p222), codename: Sleepy Sunday Serenity
Jul 25 07:52:41 as76i ruby[1514]: [1514] * Min threads: 1, max threads: 2
Jul 25 07:52:41 as76i ruby[1514]: [1514] * Environment: production
Jul 25 07:52:41 as76i ruby[1514]: [1514] * Process workers: 1
Jul 25 07:52:41 as76i ruby[1514]: [1514] * Phased restart available
Jul 25 07:52:41 as76i ruby[1514]: [1514] * Listening on tcp://localhost:3210
Jul 25 07:52:41 as76i ruby[1514]: [1514] Use Ctrl-C to stop
Jul 25 07:52:41 as76i systemd[1]: Stopping Leihs Legacy Service...
Jul 25 07:52:41 as76i ruby[1514]: [1514] - Gracefully shutting down workers...
Jul 25 07:52:41 as76i ruby[1514]: [1652] Early termination of worker
Jul 25 07:52:41 as76i ruby[1514]: [1514] === puma shutdown: 2018-07-25 07:52:41 +0000 ===
Jul 25 07:52:41 as76i ruby[1514]: [1514] - Goodbye!
Jul 25 07:52:41 as76i systemd[1]: Stopped Leihs Legacy Service.

I have to restart the service to get it up and running. LEIHS 4.0.0 runs like this but why is puma not started correctly as a service at boot?

**Comment by lachmannpablo** [comment]
Thanks for your mail. It helped me to track down my problem. When starting up manually like you described it became clear that it could not open a port. Since the port 3210 was not used by an other service, the reason for failure seems to be a network configuration problem.

The solution for my problem: leihs-legacy uses puma, a ruby webserver. puma needs IPv6 enabled when starting up. IPv6 was disabled on the machine.

This thread gave me the final hint:
https://github.com/puma/puma/issues/1062

Viele Grüße

Pablo

**Comment by nadjaweisskopf** [comment]
@HSLUwem Is your problem solved or do you need further information?

**Comment by HSLUwem** [comment]
Yes, my problem is solved. From version 4.1.0 also cougar will start correctly without having to activate ipv6.

**Comment by lachmannpablo** [comment]
Does puma start up without ipv6?
