### ISSUE TITLE
error when changing the hand out date

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#616]
@nimaai could you please have a look at this error tomorrow and see, if you find out what is wrong? I couldn't find a mistake in the data. 

Mentioned by Claudio: 

How to reproduce error: 

1. go to pool "Ausleihe Toni-Areal"
2. go to lending section
3. search for delegation "ZHdK Highlights"
4. open the hand out of this delegation
5. try to change the hand out date of the first line

--> error

<img width="767" alt="bildschirmfoto 2018-08-22 um 17 20 58" src="https://user-images.githubusercontent.com/3356016/44484875-349afd80-a64f-11e8-8d36-fbfe5ee00f76.png">

<img width="1132" alt="bildschirmfoto 2018-08-22 um 21 02 04" src="https://user-images.githubusercontent.com/3356016/44484892-47adcd80-a64f-11e8-8f00-3406912186b8.png">

I checked the delegation, it is not empty. All users of the delegation are customers and are not suspended.

- Leihs version: production - 4.19.2
- Browser version: safari and chrome

**Comment by nimaai** [comment]
@nadjaweisskopf 

In regards to the first error:

This reservation line has a delegated user (contact person) with the name "Andrea Roca" who is not the member of the delegation anymore. Unfortunately one does not see this information on the reservation line itself. Otherwise the error would be clear. For now, one can make this person member of the delegation again and proceed with the hand over and then remove him/her again.

For long term solution technically I see 2 possibilities:
1. Remove this validation for existing reservation lines. It should be enough for new ones.
2. Don't allow to remove a member from a delegation if he has still submitted or approved reservation lines for the delegation. But probably this is not the restriction one wants in running production...

In regards to the second error:

I can't reproduce it. Possibly it won't be an issue anymore if the first error is resolved.

**Comment by nadjaweisskopf** [comment]
Meeting with Matus and Nadja: we discussed, that in any state apart from state closed and deleted the user can not be removed from the delegation. The manager sees a message saying "Open Orders or contracts exist for this user, the user can not be removed." / "Offene Bestellungen oder Verträge existieren für diesen Benutzer. Der Benutzer kann nicht entfernt werden.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/04628117d2b999ed3b3db8e3a7cb8f996383473f

> If a user wants to submit an order and has been removed from the delegation, he sees a message saying: "You are no longer member of this delegation."

In regards to this, we want rather to destroy the session of that user acting as the delegation. The user has to log in again, but it's more clean and transparent in context of our application.

**Comment by nadjaweisskopf** [comment]
To be tested:
- If existing reservations / open contracts then it is not possible to remove from the delegation group
- Test basket with two browsers and two different users of the same delegation.
- Logout of user when the user is removed from the delegation - test with open sessions in browser

**Comment by nimaai** [comment]
@nadjaweisskopf There is still a question what should happen in the following use case:

- Should one be able to remove a member from the delegation, who has a signed contract in the name of the delegation? Scenario: such a member leaves ZHdK.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/7cdffaa53225a9f215ad116e0adc083802d561cb
