### ISSUE TITLE
Templates image

### ISSUE THREAD

**Issue by transat** [leihs/leihs#63]
Changing category images is working great in the latest version. But would it be possible to also edit the 'templates' image the same way? No big deal as it can always be changed with some CSS but it would be nice all the same.

**Comment by nadjaweisskopf** [comment]
Changing the picture in the categories is not the best solution because inventory managers of every pool can change the picture - the last one wins.
But still, unless we have another solution, I would implement the same behaviour for the template. So all inventory managers can change the picture of the template.

![bildschirmfoto 2017-11-15 um 16 52 46](https://user-images.githubusercontent.com/3356016/32845980-6eeb9f5e-ca26-11e7-9271-6d16c7e33361.png)
