### ISSUE TITLE
Order can not be submitted

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#635]
#### Expected behaviour
The lending mgr. would like to submit the order. 

#### Actual behaviour
The lending mgr. of the pool "Ausleihe Toni-Areal" need to submit an order and gets an error.

![bildschirmfoto 2018-10-10 um 16 30 32](https://user-images.githubusercontent.com/3356016/46743696-ed71d600-cca9-11e8-8068-425f0b1541f8.png)

#### Steps to reproduce
1. go to pool "Ausleihe Toni-Areal"
2. search for "ZHdK Immersive Arts Space"
3. Try to approve the order
4. nothing happens
5. check the error in the console

#### Specifications
- Leihs version: 4.19.3 production / staging / test
- Browser version: safari / opera / chrome

**Comment by nimaai** [comment]
The problem is the same as in https://github.com/leihs/leihs/issues/559.

An order can not have multiple delegated users. There is a respective validation in backend which triggers on any update of an order.

The frontend however allows this thing to happen: multiple users of a delegation can simultaneously create unsubmitted reservations for the same delegation.

@nadjaweisskopf This use case and specific workflows which lead to it need to be analysed. Some relevant questions are:
- Do we acknowledge this as a valid use case or prevent it to happen in borrow?
- If ok, shall we track multiple delegated users after submit? If no, shall we track only the one who submitted the order and put him on all its reservations?
- If there are multiple delegated users, do we notify all of them via email?

**Comment by nadjaweisskopf** [comment]
@nadjaweisskopf Ask A.B. how the working process is
