### ISSUE TITLE
Multilingual Procurement with simple solution

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#663]
- ensure singular / plural
- nadja checks translation

**Comment by eins78** [comment]
most simple solution that technically works: 
https://github.com/leihs/leihs/commit/1a124bf602b30aee9c2b79a50a032e7ddd73301b

deployed here https://mfa.ruby.zhdk.ch/procure/

Looks weird when switching the language because it hard-reloads 2 times. On the other hand it is very little code.

The UI components/affordances are not translated yet. I suggest doing that when we decide on a general solution.
