### ISSUE TITLE
Wrong Modelname are shown when Ausleihe is scanning in a Package

### ISSUE THREAD

**Issue by gurmir** [leihs/leihs#675]
#### Expected behaviour
Roger and Pius from Ausleihe have to do some Packages. But sometimes the wrong device is shown.

#### Actual behaviour
They want to scan Inventory Codes to for a Package. Sometimes when they scan a Model (Mobile Scanner and USB-Scanner as equal) it brings a wrong device in the Package. In this case the scan a Audio receiver and the scanner brings a Sony Camera. 

#### Steps to reproduce
1. Go to Invenory Pool Ausleihe Toni-Areal
2. Go to Inventory
3. Research for a Model who's a Package
4. Scan the Inventory Code
5. A wrong Model are shown.

**Correct Inventory No.**
![img_20181217_1349573](https://user-images.githubusercontent.com/37148448/50088515-8b7ea100-0203-11e9-8b0d-00095de57c9e.jpg)

**After Scanning with USB - / Mobile Scanner**

![img_20181217_1132225](https://user-images.githubusercontent.com/37148448/50082144-8532f980-01f0-11e9-9f1b-07c23d41417a.jpg)

#### Specifications
- Leihs version: 5.0
- Browser version: Firefox, Safari, Chrome

**Comment by nimaai** [comment]
@gurmir Could you please provide the exact inventory code they are scanning? Maybe by making a picture and uploading it here.

**Comment by eins78** [comment]
2 things are happening in combination, producing this surprising behaviour:
- search only shows "borrowable" items, the example item is not, so the result is empty => very likely this is a bug
- if a search has no results, the default results (from empty search) is shown => definitely a bug

**Comment by nimaai** [comment]
Regarding point 1: Unborrowable items are searched right now, but this specific item is not in the pool (neither through `owner_id` nor `inventory_pool_id`.

**Comment by eins78** [comment]
code reviewed and feature manually tested ✅

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/50a896d353ceb80edc5a8575f121ed138528ef08

**Comment by eins78** [comment]
@nadjaweisskopf yes and now. the commits mentioned above are indeed part of RC.3, but the fix _does not work with the barcode scanner_ (i just tried). Will look into it tomorrow.

For the record, this is the intended result (right now only works when using the keyboard instead of the barcode scanner):
![screen shot 2019-02-05 at 16 55 05](https://user-images.githubusercontent.com/134942/52286181-09d80380-2968-11e9-876c-b48e18673d14.png)

**Comment by nadjaweisskopf** [comment]
@eins78 yes, ok. But Rogers team works with the scanner. So I would accept this ticket as soon as the scanning part works too. Ok?

**Comment by nadjaweisskopf** [comment]
@eins78 with the keyboard it worked like expected.

**Comment by eins78** [comment]
@nadjaweisskopf I propose that we remove the behavior of showing a "default result list" when no search term is entered. Fixing the bug _and_ keeping this would be much complicated/take longer and does not seem worth it.

**Comment by nadjaweisskopf** [comment]
Yes ok. I could't reach roger but i can't think of a use case where this feature could be of any value.

**Comment by eins78** [comment]
@nadjaweisskopf Fix will be in the next RC. I tested with the scanner, the correct result is now shown. 
Then I compared against the current version (prod) and found that the scanner never worked correctly, it just always selects the first result in the currently displayed list. 
But: Since the scanner presses 'Enter' after the scanned, the user has to be careful if something is in the field already when scanning. Conversely, in this form the user has to be careful with the scanner anyhow.
Conclusion: Its still not perfect, but not showing the default list anymore when clicking in the empty field solves the biggest problem as described in this issue :/

**Comment by eins78** [comment]
@nimaai for next RC: 
https://github.com/leihs/leihs_legacy/commit/59873a1c0c6d4d0efde02df41b8c449ce709de4e

**Comment by gurmir** [comment]
Test with handscanner in Staging was good,

**Comment by nadjaweisskopf** [comment]
@nimaai 
- if I scan the same item twice, I get an empty list. I would expect to see a msg. like "already added"
- If I scan the item but the cursor is not inside the field, the global search is activated.

**Comment by nadjaweisskopf** [comment]
@nimaai For our lending department these two cases mentioned above are mandatory to be able to deploy. Could you already find solutions?

**Comment by nimaai** [comment]
@mfa Did you already have a look in regards to:

> * if I scan the same item twice, I get an empty list. I would expect to see a msg. like "already added"
> * If I scan the item but the cursor is not inside the field, the global search is activated.

?

**Comment by nadjaweisskopf** [comment]
I will create a ticket for the two points mentioned above
