### ISSUE TITLE
Procurement supplier field not working

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#697]
The frontend client is not sending `supplier_name` as graphql variable in the mutation request.

**Comment by eins78** [comment]
@nimaai Realisation when trying out the fix: we should also test if a form field can be *emptied*. 
In this case it makes a difference if the field is sent as `""` oder `null`, because there is an `supplier_name_is_not_blank` contraint.
Conversely, we could aim to have the API handle such cases (if there is "not blank" constraint, it should "nullify blanks"). I guess that would be more in line with our approach (its kind of a buisiness logic/frontend does not know which fields can have blanks an which not).
