### ISSUE TITLE
Render Error when creating first user.

### ISSUE THREAD

**Issue by gcioffi** [leihs/leihs#735]
#### Expected behavior

Create first user.

#### Actual behavior

Render Error when accessing leihs website for the first time.

#### Steps to reproduce

Follow instructions as in https://github.com/leihs/leihs-instance/blob/master/GUIDE.md
Deployment completed successfully.

#### Related issues 

Same issue as here #725 
I have the latest ansible version. 

#### Specifications
- Leihs version: 5.0.4
- Browser version: Mozilla Firefox 68.0
- System version: Debian stretch (managed node), RedHat 8 (Control node).
- MySQL/PostreSQL version: PostgreSQL 10.9

**Comment by gcioffi** [comment]
Any idea why this happens? I have been working on it for a while but I do not see what goes wrong.

**Comment by sdenz** [comment]
Is there already a solution to the problem mentioned above?

I am getting the same message in my web browser after deployment when accessing leihs website for the first time.

**Expected behavior**
Create first user.

**Actual behavior**
Render Error when accessing leihs website for the first time.

**Steps to reproduce**
Follow instructions as in https://github.com/leihs/leihs-instance/blob/master/GUIDE.md
Deployment completed successfully.

**Related issues**

Same issue as here #725
I have the latest ansible version.

**Specifications**

- Leihs version: 5.2.3
- Browser version: Google Chrome 87.0.4280.88 (same error in Safari or Firefox)
- System version: Ubuntu 18.04 (managed node), macOS 10.14.6 (Control node).
- MySQL/PostreSQL version: PostgreSQL 10.15
