### ISSUE TITLE
Audits download out of memory & optimization of UI

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#739]
Right now this can happen for a big time range when downloading audits:

`Unclassified error, see the server logs for details.`

`Jul 18 09:09:20 zhdk-leihs-staging leihs-admin[81682]: [WARN  Jul-18-Thu_09:09:20 leihs.core.ring-exception manifold-pool-2-38]   THROWABLE: java.lang.OutOfMemoryError: Java heap space`

I assume this can't be entirely prevented.

But some UI optimisations would help:
- Show the timestamp of the oldest audit so that the user has an idea how big is the data he/she is about to download.
- Then perhaps default the "until" date to the date of oldest audit + 1 month. Then the user can just keep on clicking on download and it should work.

**Comment by DrTom** [comment]
Have a look how the archiver works. A similar workaround as mentioned is implemented there. 

I am aware of those problems. I considered preventing them right away but decided not to because of the involved effort. @eins78 and me discussed this during @nimaai absence. 

I don't agree to implement these adjustments. They don't really solve the problem. Some sort of more fine grained pagination (iterator if you like to call it that way) would. But as mentioned involved effort... 

This feature is not even accessible for admins, only sysadmins which is basically just us. So I don't think it is worth it.  

Let us discuss this in the next planing.
