### ISSUE TITLE
Items not models in tooltips after handover

### ISSUE THREAD

**Issue by transat** [leihs/leihs#76]
A useful feature would be for tooltips to reveal what items a user has taken out, rather than the model of the item. For example, the tooltip should read "tripod-03" rather than "Manfrotto Tripod" once an item has been handed over.

**Comment by nadjaweisskopf** [comment]
A late response to your question: 

Here is the way we handle take backs if the person is not present:

1. Enter the model name or inventory-code in the global search field on the top left hand side of the page
2. Scroll down to where the contracts are listed.
3. There you find the open contracts (marked with button "take back") quickly and can find the right user by checking the take back date in the popup.

I hope this helps, otherwise please reopen this issue.
