### ISSUE TITLE
LDAP Authentication?

### ISSUE THREAD

**Issue by JSY-Ben** [leihs/leihs#776]
Hi there. I am testing Leihs to use at our university for our AV Equipment store. I know Version 5+ has a new authentication system. I must admit i'm not expert enough to create this, but was wondering how much work it would be to create an LDAP/Active Directory plugin to allow users from our locally based Active Directory server to authenticate to Leihs. We are happy to pay for this if it requires development time and you would be willing :)

Many thanks,
Ben

#### Specifications
- Leihs version: 5.1.7
- Browser version: Safari 13.0.5
PostreSQL version: 10.11

**Comment by DrTom** [comment]
Hi, 

there are two or three examples of authentication adapters in the leihs main repo. 
The one most close to your environment is maybe the following:

https://github.com/leihs/azure-active-directory-leihs-authentication-system

Can you check if it would be possible to adapt this one? This one does not work with LDAP (and we really disencourage the old LDAP way where the organization password needs to pass through leihs or for that matter any application). Possibly OpenID Connect or something similar is available in your environment?

**Comment by DrTom** [comment]
Since you are in a university environment there is also a second option via switch aai: 

https://github.com/leihs/leihs-zhdk-switchaai-shibboleth-auth-system

It might also be possible to modify this to use edu-id. I am not sure but the technical foundation seems to be similar. 

We can give you a reference for "payed development" if you need help to adopt  to your environment.

**Comment by DrTom** [comment]
Closing this now.
