### ISSUE TITLE
Error when saving item

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#831]
When saving the item I get an error. 

How to reproduce: 
1. go to inventory park "DDK Veranstaltungstechnik"
2. search for item "Ptk24000"
3. save item without changing any information
4. error as shown in print screen

<img width="930" alt="Bildschirmfoto 2020-06-02 um 09 34 08" src="https://user-images.githubusercontent.com/3356016/83493090-8e7f5700-a4b4-11ea-8bf6-2b54667c11bf.png">

**Comment by nadjaweisskopf** [comment]
When deactivating a pool all items need to be moved to other pools first. Test what happens, when item is moved and responsible park is deactivated.

**Comment by nimaai** [comment]
A pool can't be deactivated if it _has or owns items which are not retired_.

This is the case of this item. It is retired. The responsible pool which is deactivated is set as responsible but not shown in the UI. This is the first issue. The second issue is the error itself when saving the item. We need to take look at the respective validation.

**Comment by nimaai** [comment]
Ok, so I have done 3 things so that everything is consistent:

1. Fix the error message
2. New validation: an item can have an **inactive owner** OR **inactive responsible** ONLY if it is **retired**. This is basically the statement of my previous comment the other way round.
3. The dropdowns on item edit page and inventory helper include now inactive pools too (with the suffix `(inactive)`). Otherwise 2. cannot be done.

@nadjaweisskopf D'accord?

**Comment by nadjaweisskopf** [comment]
@nimaai we decided to show all pools, on top the active ones, on the bottom the inactive ones. Both lists are alphabetically sorted.
