### ISSUE TITLE
Check daily view 24.8. 

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#842]
#### Expected behaviour
I would expect to see the next five days starting today. When pressing on the next day on the button on the top, then I would expect to see the day after these five days. Seems like a bug. 

#### Actual behaviour
Today is shown but then the next date is already the 24.8. The dates inbetween are missing. When I press on the next day, the date 25.8. is shown. 

#### Steps to reproduce
1. go to Ausleihe-Toni-Areal
2. Check the daily view
#### Specifications
- Leihs version: 5.2.0
- Browser version: safari
- MySQL/PostreSQL version:current

**Comment by nimaai** [comment]
@nadjaweisskopf The days missing are holidays. It seems to be intentional. Do we want to change that? Some of the holidays are named as "Rücknahmen". It seems to me that the pool is operational in that time, but want to prevent any new (further) reservations for this time span.

**Comment by nadjaweisskopf** [comment]
@nimaai Let's just show today and then the next four days. That might make more sense. They have a lot of take backs in two days which are not shown. For the backend managers the work seems to continue.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/7ea8feed4bd9227cd051d2514ebe85dfc85d637e

@nadjaweisskopf Daily view now includes all days, even weekends. The problem was that some pool had all days in week closed so the daily view was in a dead-end. It could neither find last nor next open days. This pool had some hand overs though.
