### ISSUE TITLE
Trying to deploy 5.0.1 as part of an upgrade from v4.  (set BOOT_AS_ROOT=yes to force) error.

### ISSUE THREAD

**Issue by AnthonyHunt1** [leihs/leihs#847]
#### Expected behaviour
initial deployment.

#### Actual behaviour
fails with:
TASK [leihs-mail-install : create jar] **********************************************************************************
fatal: [172.16.11.43 -> localhost]: FAILED! => changed=true 
  cmd: |-
    set -eux
     DEPLOY_DIR='/arthouse-leihs/leihs/deploy'
     cd $DEPLOY_DIR/../mail
     $DEPLOY_DIR/bin/boot uberjar
  delta: '0:00:00.051081'
  end: '2020-06-12 14:51:45.882277'
  msg: non-zero return code
  rc: 1
  start: '2020-06-12 14:51:45.831196'
  stderr: |-
    + DEPLOY_DIR=/arthouse-leihs/leihs/deploy
    + cd /arthouse-leihs/leihs/deploy/../mail
    + /arthouse-leihs/leihs/deploy/bin/boot uberjar
    Exception in thread "main" java.lang.reflect.InvocationTargetException
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at Boot.main(Boot.java:257)
    Caused by: java.lang.Exception: refusing to run as root (set BOOT_AS_ROOT=yes to force)
            at boot.App.main(App.java:438)
            ... 5 more
  stderr_lines:
  - + DEPLOY_DIR=/arthouse-leihs/leihs/deploy
  - + cd /arthouse-leihs/leihs/deploy/../mail
  - + /arthouse-leihs/leihs/deploy/bin/boot uberjar
  - Exception in thread "main" java.lang.reflect.InvocationTargetException
  - "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
  - "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
  - "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
  - "\tat java.lang.reflect.Method.invoke(Method.java:498)"
  - "\tat Boot.main(Boot.java:257)"
  - 'Caused by: java.lang.Exception: refusing to run as root (set BOOT_AS_ROOT=yes to force)'
  - "\tat boot.App.main(App.java:438)"
  - "\t... 5 more"
  stdout: ''
  stdout_lines: <omitted>

#### Steps to reproduce
Deploy to Debian Buster LAPP server.
Follow installation guide - installing needed modules etc
run "sudo ./scripts/deploy"

#### Specifications
- Leihs version: 5.0.1
- Browser version: N/A
- MySQL/PostreSQL version: Postgres 12

**Comment by winampdevil** [comment]
type in the following commands before you start the deploy-process:

;become root at the control machine
sudo su

;export variables as described in the guide
export LEIHS_HOSTNAME="leihs.example.com" 
export LEIHS_HOST_USER="root"

;important for your problem
export BOOT_AS_ROOT=yes 

;begin deployment
./scripts/deploy

**Comment by AnthonyHunt1** [comment]
Thanks! I appreciate it! Didn't try it that way around.  Maybe worth the "Hosting Guide" being updated to reflect the change to su? Probably would have saved me a day?

Currently stuck elsewhere with a proxy issue. Joys!

**Comment by nadjaweisskopf** [comment]
@nimaai @DrTom could you please check if we need to enhance our decumentation?

**Comment by eins78** [comment]
@AnthonyHunt1 is there a reason why you're running the deploy with `sudo ./scripts/deploy`? Because that causes ansible and all the local compilation to be run as root (on your local machine, not the server). Compiling as root is generally not recommended, that's why you've run into this issue with boot. 
While the specific workaround (`BOOT_AS_ROOT`) works, there might be more issues later on. If you really need to run ansible as root in your environment I would be interested why.

**Comment by AnthonyHunt1** [comment]
Yes, there’s a vert good reason.... it won’t install without it.

If you go back to a fresh clean minimal Ubuntu 9; and install try to install 5.0.1 through 5.0.4; it won’t install any other way. You end up with various errors at different points of the install process. The only way to make it work through those versions was by “sudo su” and then still “sudo” the install.

I literally spent about a week going from that stage forward. Thankfully I’m now fully migrated up to 5.1.10 so don’t need to go through that nightmare again....

You’ll see a gist in another issue that I posted with the only working recipe I could find.

There were also other elements that needed installing or clarifying In the documentation too...

**Comment by eins78** [comment]
Thanks for the answer. I am glad to hear that your environment should not normally need sudo (if it was needed to get older versions of leihs to work). Going forward you should not need to run it as root anymore (but if you just switch now expect some permission issue of course).

> There were also other elements that needed installing or clarifying In the documentation too...

Yes, I am aware and most (all?) of that should be fixed in version 5.2.0 and the updates to `leihs-instance`. 
Note that this does not affect/fix old versions of leihs but at the same time there is no need to go trough every patch version, so you could directly upgrade to 5.2.0.
