### ISSUE TITLE
Problem with Helper and Move/Supply Catge field

### ISSUE THREAD

**Issue by ClaesFredo** [leihs/leihs#85]
Hi

Let me start by thanking you all for a very well made software. LEIHS is a joy to use. 

I am using version 3.19.1 where I found a problem when using Helper. Updating the

**Comment by ClaesFredo** [comment]
Clumsy fingers - trying once more

Hi

Let me start by thanking you all for a very well made software. LEIHS is a joy to use.

I am using version 3.19.1 where I found a problem when using Helper. Updating the Move field using the Helper function, I find that this blanks the Supply Category field. I tried the current live demo and find the same problem there as well. 

My wife has tweaked LEIHS a bit to suit my needs so she is the one in the know here. When checking the database it all looks OK, but the Supply Category selection does not show. So, this is not a major bug in any way.

**Comment by psy-q** [comment]
Ah, the "Move" and "Supply Category" things are actually something I'm quite ashamed of. They are fields that are very specific to the ZHdK and at some point I would like to get rid of them and make that part configurable so each leihs instance can choose their own way of handling it.

Right now you have to set "Inventory relevant" to "yes" to get the "Supply Category" required field. It has a dependency so that only things that are inventory relevant need to have a supply category.

The background here is that not all inventory that the ZHdK keeps in leihs is actually considered inventory, some departments keep their costumes or video games in there. And to prevent a double-stocktake (e.g. the video games would already be inventoried by the library in a different system, so it isn't required that they're inventoried again by the department lending them), leihs now contains the field "inventory relevant". Things that are not inventory relevant from leihs' view do not count toward the stocktake.

The downside of this is that when something *is* inventory relevant, management expects to know which supply category (again, a Swiss federal/cantonal thing) it belongs to, so that accounting knows what to do with the initial price of the item.

Very complicated, boring and bureaucratic and I hope we can soon get rid of it. Please try setting "Inventory relevant: yes" and let us know if the field appears then. I tried it out locally and it seems to.

**Comment by ClaesFredo** [comment]
Hi

For what it is worth. My wife has an MSc in Compter Sciences + one in Mechanical Engineering and she tells me that she never has seen a code as well documented and well structured as LEIHS. As I see it, you have nothing to be ashamed of. 

What you write works in also my version of LEIHS. It does not really solve the problem (for me) as I use LEIHS to keep track of measurement instrumentation and have renamed the Move field to Calibration type and would like to edit the move field independent from the Inventory type field. 

I guess this is because I live in a different Canton? :)

Over2Jo
Claes

**Comment by psy-q** [comment]
Oh, you shouldn't just rename fields. If you do go the way of customizing `app/models/field.rb`, it's best if you remove the fields you don't want and add new ones with new IDs. Maybe you can pick an ID range for yourself, let's say 10000 - 11000, so you're not likely to clash with anything.

field.rb is undocumented and not officially supported, but so far it's the cleanest way we have for you to create custom fields. We're planning to expand this so that you can for example make a plugin out of your field configuration. Then, when you install a vanilla leihs, you can just add your field configuration plugin and there's your custom instance. That will also reduce or eliminate clashes.

I would avoid changing the database itself to add fields, etc., since future migrations might change the DB in a way that interferes with your customizations, and then you'd be either stranded with an old leihs version or forced to port your changes to the new one. 

We've debated creating a field editor that allows changing the database through a GUI, but another team here has done this sort of work before for another system and you end up creating a bad database on top of a good database and a very brittle GUI on top, so we're not going that way for now. We'd rather keep customizations in some config files.

**Comment by psy-q** [comment]
Just to keep everyone in the loop, we're now hard at work making the fields customizable through the web interface by exposing our tried-and-true field API that has been stable for over two years.

It should become, while not super-trivially easy, at least possible and reliable to customize each leihs instance's fields before the end of this year.

**Comment by psy-q** [comment]
We actually delivered that last year and are hoping for people to test and comment. The guide is here:

https://github.com/leihs/leihs/wiki/Fields
