### ISSUE TITLE
Enhancement - why not list the LEIHS version, e.g. in the footer section?

### ISSUE THREAD

**Issue by ClaesFredo** [leihs/leihs#86]
Hi

Just a thought - it might simplify discussions. 

/Claes

**Comment by psy-q** [comment]
I put this into the ZHdK's Pivotal Tracker as https://www.pivotaltracker.com/story/show/95031672

**Comment by psy-q** [comment]
One issue here is that depending on where you installed leihs from, the version is in a different place, or not there at all. Installations from git would have to show the tag they checked out or, if there is no tag, the commit SHA of the local branch's HEAD (for lack of a true version string).

If you installed from a tarball or zipball, none of that information is there and GitHub does not seem to have a mechanism to add it. So we would have to manually add version information to each tagged release, but that would immediately be outdated when anyone pushes anything to master.

Or we would have to change the process so that before tagging something on master, a version file needs to be added by hand by whoever is tagging and then removed again on master. Otherwise people using an instance from master would see the wrong version information, and that would create more confusion than it does good.

Right now I can't think of a bulletproof and automated way to do this, short of writing something that uses the GitHub API to list all releases, download the zipballs/tarballs, add the version file based on the tag, repackage the archives and push new ones up to the releases, replacing the old ones. That's super-heavyhanded and error-prone.

Anyone have better ideas? Or maybe experience with this? Is it negligible that people using the master branch would have wrong version information?

**Comment by psy-q** [comment]
I think that `git describe --tags` might be enough to do this. Here's a plan:

* We could detect whether git exists on the server machine.
  * If it does we detect if the current leihs directory has a .git subdirectory.
  * If it does we pipe the output from `git describe --tags` into a footer and cache the result for some time (don't want to subshell on every request).
* If there is no git and no .git, this suggests a tarball install, in that case we just read the version string from some file.

How does that sound? Is it too dangerous to subshell to a git process? We're not passing any user input, just the hardcoded `git describe --tags` is enough.

**Comment by AnthonyHunt** [comment]
This sounds ok to me? if it's all hard coded I don't think it could hurt?

**Comment by nadjaweisskopf** [comment]
In the next release we will list the leihs version in the footer of leihs. 
Please view ticket https://github.com/leihs/leihs/issues/251
