### ISSUE TITLE
external_base_url in host_vars/server.yml not populating correctly

### ISSUE THREAD

**Issue by AnthonyHunt** [leihs/leihs#872]
#### Expected behaviour
external_base_url gets written to the database on deployment and should be fully qualified for redirects to work correctly.

#### Actual behaviour
external_base_url gets written as variable used in LEIHS_HOSTNAME ie. external_base_url : ${LEIHS_HOSTNAME}

if, after initial deployment, it is manually changed to fqdm ie "https://leihs.example.com" it deploys properly.

#### Steps to reproduce
export LEIHS_HOSTNAME="leihs.example.com"
export LEIHS_HOST_USER="root"
export BOOT_AS_ROOT=yes
./scripts/deploy

#### Related issues 
see https://github.com/leihs/leihs_zhdk-inventory/tree/master/settings for examples of how it should look.

#### Specifications
- Leihs version: 5.1.10 & 5.1.11
- Browser version: Safari, Chrome
- MySQL/PostreSQL version: N/A

**Comment by eins78** [comment]
* The env var `LEIHS_HOSTNAME` is only needed for the example commands like from the GUIDE.md that you run directly in your shell. So its only needed for the initial setup so all the config files are generated correctly from the templates.

* `external_base_url` must be configured in the settings file (yaml but not part of ansible config) and be in the form of "https://leihs.example.com" (might have been generated wrong because of https://github.com/leihs/leihs-instance/issues/5)

* `leihs_external_hostname` must be configured in the ansible config (`host_vars/leihs.example.com.yml`) and be in the form of "leihs.example.com"
