### ISSUE TITLE
Amount does not fit to the filter

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#939]
https://tom.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/entitlement-groups/b985be38-962b-49ea-a601-590b7d8dc84f/users/?account_enabled=&is_admin=&org_id=&page=1&per-page=50&term=&membership=direct

When chosing the filter "members and non members" there are hundreds or thousands of users listed. But the amount on the top shows the amount of users added directly or indirectly to the entitlement group. As a user I would expect the amount fits to the filter I have chosen. 

related issue: #900

**Comment by DrTom** [comment]
Hmm, yes but then the title does not make much sense because the users are not "in" the group. At any rate: with some other similar "numbering in the title" we decided to remove the count information completely from the title. I guess this is the simple and consistem way. The counts are shown on the inventory-pool page, too. So this information is duplicate anyways. 

I am going to remove the count.

**Comment by DrTom** [comment]
https://github.com/leihs/leihs-admin/commit/bbe9317c11d7fc5fc721033d31daaab65a6dbd13

**Comment by nadjaweisskopf** [comment]
@DrTom Ok. For now let's leave it away. But when testing the filters I notice I always scroll down to have a feeling how many users are shown when selecting a filter. In the end it would be easyser for the user if we would show the number of filter results.
