### ISSUE TITLE
Create user requires e-mail address 

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#989]
White space filled e-mail address cause create user to fail. Technically not wrong bad UX.

**Comment by eins78** [comment]
Seems to be solved in the meantime:
* when entering only whitespace (including ` `), email is NULL after saving
* when entering an invalid email (like `x`), the form can't be submitted (browser validation, because the input field has the correct `type=email`)
* when entering a minimally valid email it works: `a@b` is sufficient. We could enforce something more strict in the frontend if needed (`<input type=email pattern=$SOME_REGEX>`).
